### ISSUE TITLE
[BUG] alluxioruntime-controller error converting YAML to JSON: yaml: line 29: did not find expected key

### ISSUE THREAD

**Issue by uniqueni** [fluid-cloudnative/fluid#1155]
**What is your environment(Kubernetes version, Fluid version, etc.)**
 
image:  fluidcloudnative/alluxioruntime-controller:v0.7.0-542cd8f

**Describe the bug**
       when I use image: fluidcloudnative/alluxioruntime-controller:v0.7.0-542cd8f,  alluxioruntime-controller report an error: 'Error: YAML parse error on alluxio/templates/worker/statefulset.yaml: error converting YAML to JSON: yaml: line 29: did not find expected key' 
    I found  this value.yaml line29 is initUsers's 'args'  
> initUsers:
  enabled: false 
  image: registry.cn-hangzhou.aliyuncs.com/fluid/init-users
  imageTag: v0.3.0-1467caa
  imagePullPolicy: IfNotPresent
  args: "1000"
  envUsers: ""
  envTieredPaths: ""
  dir: ""

![image](https://user-images.githubusercontent.com/44921652/142768757-4e061f3d-583e-461a-b150-aa5d7038de58.png)

**What you expect to happen:**

**How to reproduce it**

**Additional Information**

**Comment by cheyang** [comment]
May I know where did you get this image tag? Seems it's still in development: https://github.com/fluid-cloudnative/fluid/commits/542cd8f

**Comment by cheyang** [comment]
And I think you need check `alluxio/templates/worker/statefulset.yaml` by using `helm lint alluxio` inside the docker container.

**Comment by uniqueni** [comment]
from  dockerhub... I think it's lastest image
https://hub.docker.com/layers/fluidcloudnative/alluxioruntime-controller/v0.7.0-542cd8f/images/sha256-aca89dd24839b3f6d5d3b93c630603e69a50d3066939d8b1ca2a12f028794457?context=explore

now I try again user image tag v0.7.0-e76b195
it report an anohter error when create master pod: 
![image](https://user-images.githubusercontent.com/44921652/142769907-6c12d238-fa4d-480b-8691-546c51d3fee6.png)

Is tag v0.7.0-e76b195 the latest image?

**Comment by uniqueni** [comment]
> May I know where did you get this image tag? Seems it's still in development: https://github.com/fluid-cloudnative/fluid/commits/542cd8f

from  dockerhub... I think it's lastest image
https://hub.docker.com/layers/fluidcloudnative/alluxioruntime-controller/v0.7.0-542cd8f/images/sha256-aca89dd24839b3f6d5d3b93c630603e69a50d3066939d8b1ca2a12f028794457?context=explore

now I try again user image tag v0.7.0-e76b195
it report an anohter error when create master pod: 
![image](https://user-images.githubusercontent.com/44921652/142769907-6c12d238-fa4d-480b-8691-546c51d3fee6.png)

Is tag v0.7.0-e76b195 the latest image?

**Comment by uniqueni** [comment]
> > May I know where did you get this image tag? Seems it's still in development: https://github.com/fluid-cloudnative/fluid/commits/542cd8f
> 
> from dockerhub... I think it's lastest image https://hub.docker.com/layers/fluidcloudnative/alluxioruntime-controller/v0.7.0-542cd8f/images/sha256-aca89dd24839b3f6d5d3b93c630603e69a50d3066939d8b1ca2a12f028794457?context=explore
> 
> now I try again user image tag v0.7.0-e76b195 it report an anohter error when create master pod: ![image](https://user-images.githubusercontent.com/44921652/142769907-6c12d238-fa4d-480b-8691-546c51d3fee6.png)
> 
> Is tag v0.7.0-e76b195 the latest image?


Maybe it’s because my minio cluster is offline. I will close this issue after I make sure tomorrow ...
very thankful

**Comment by cheyang** [comment]
You can get the image tag of stable version from https://github.com/fluid-cloudnative/fluid/blob/master/charts/fluid/fluid/values.yaml#L9

**Comment by uniqueni** [comment]
> You can get the image tag of stable version from https://github.com/fluid-cloudnative/fluid/blob/master/charts/fluid/fluid/values.yaml#L9

I use new images from   https://github.com/fluid-cloudnative/fluid/blob/master/charts/fluid/fluid/values.yaml#L9
but it can't work:

![image](https://user-images.githubusercontent.com/44921652/142837218-5ea361b3-f619-4dec-94c6-b5b25e56bb64.png)

**Comment by uniqueni** [comment]
> > You can get the image tag of stable version from https://github.com/fluid-cloudnative/fluid/blob/master/charts/fluid/fluid/values.yaml#L9
> 
> I use new images from https://github.com/fluid-cloudnative/fluid/blob/master/charts/fluid/fluid/values.yaml#L9 but it can't work:
> 
> ![image](https://user-images.githubusercontent.com/44921652/142837218-5ea361b3-f619-4dec-94c6-b5b25e56bb64.png)

I found this error from alluxioruntime-controller logs
![image](https://user-images.githubusercontent.com/44921652/142841562-cf2c81ee-e721-40d5-8c7c-8468d004d0d4.png)

**Comment by uniqueni** [comment]
> > > You can get the image tag of stable version from https://github.com/fluid-cloudnative/fluid/blob/master/charts/fluid/fluid/values.yaml#L9
> > 
> > 
> > I use new images from https://github.com/fluid-cloudnative/fluid/blob/master/charts/fluid/fluid/values.yaml#L9 but it can't work:
> > ![image](https://user-images.githubusercontent.com/44921652/142837218-5ea361b3-f619-4dec-94c6-b5b25e56bb64.png)
> 
> I found this error from alluxioruntime-controller logs ![image](https://user-images.githubusercontent.com/44921652/142841562-cf2c81ee-e721-40d5-8c7c-8468d004d0d4.png)

I found env from master pod, it  doesn't have this variable
![image](https://user-images.githubusercontent.com/44921652/142842602-a2dde6e4-c2c1-41ee-9345-34237da82093.png)

**Comment by uniqueni** [comment]
I fixed it , because of master and worker’s resources to tiny...
