### ISSUE TITLE
[BUG] when the image address like "172.27.xx.xx:35000/alluxio/alluxio:2.7.0", parse alluxioruntime image and imagetag error

### ISSUE THREAD

**Issue by uniqueni** [fluid-cloudnative/fluid#1293]
**What is your environment(Kubernetes version, Fluid version, etc.)**
2.7.0

**Describe the bug**
when the image address like "172.27.xx.xx:35000/alluxio/alluxio:2.7.0",
after parse, image and imagetag :
![image](https://user-images.githubusercontent.com/44921652/146745468-9482acc9-2c5b-4437-aa12-08345dde3a23.png)

i found this code ,this does not cover scenes with multiple ”:“
![image](https://user-images.githubusercontent.com/44921652/146745828-47a93a34-8df6-412e-96aa-74b66a82dbbc.png)

**What you expect to happen:**

**How to reproduce it**

**Additional Information**

**Comment by uniqueni** [comment]
i have a pr for this bug
https://github.com/fluid-cloudnative/fluid/pull/1294

**Comment by cheyang** [comment]
Thanks very much. It's merged.
