### ISSUE TITLE
团队学生抱团来刷 Star

### ISSUE THREAD

**Issue by chengtae** [fluid-cloudnative/fluid#1308]
如题，就是 刷个 Star，顺便发个 issue，另需要 Star 建议淘宝买

**Comment by cheyang** [comment]
@chengtae 

您好，我是这个项目的联合创建者、贡献者，也是一名普通的工程师，看到您的issue，我感觉非常心痛。首先向您真诚的道歉，让您产生了困恼，请允许我做一些解释和澄清。这个项目的贡献者来自于不同的公司和高校，没有专业的运营人员，几位项目参与者和社区的小伙伴（全是技术同学）也都是在用自己的业余时间和朋友圈，向可能感兴趣的人宣传和分享这个开源项目及技术。

大家的本意是欢迎更多人了解和支持这个开源技术。我们已经了解清楚，最近有参与社区的伙伴在向身边计算机方向的朋友宣传分享了Fluid项目及技术。宣传消息在层层传播过程中，意思发生了变化，让人产生了误解，从而发生了困扰您的情况。对此我们要特别说明：我们这个项目所有创建者都不能接受任何强迫或暗示别人必须star的行为，任何人都可以unstar或者无视我们的宣传。我们也愿意向对您提出“要求给star”的人做出澄清，如果需要的话可以联系我们。 ** 我们是站在您一边，坚决抵制这种行为!**
我们相信我们正在解决开源社区遇到的一些有意义的技术问题，我们在用自己的业余时间对社区做贡献。如果您注意到，我周末也在贡献这个项目，我把这个项目当成自己的baby，我是充满了热情来维护这个项目，也在花真心在呵护。从我心里我和您一样，不允许它受到玷污。下面，我们会做的事情：

1）我们后续的宣传会更聚焦在Fluid的技术原理上，并且显式说明不接受任何要求star的行为。
2）我们会持续认真把这个开源项目做好，专注于这个开源项目技术本身，也欢迎您参与进来（如果感兴趣的话）。

最后，我代表社区开发者团队认真地说一句：感谢您的反馈，这非常重要。这促使我们认真思考如何来做好开源社区的运营和开源技术的宣传。另外对给您带来的困扰，也向您深深的致歉，以上是我的澄清和思考。

另外您可以取消小星星，我对给您带来的困扰表示非常的歉意。我们当然更希望您有时间了解一下这个项目，这是我们的初衷。再次表示歉意。

**Comment by uniqueni** [comment]
忍不住说句话 先申明我不是这个社区的维护者 我只是Fluid众多使用者之一  咱们公司最近需要使用Alluxio 为了方便接入 我们大佬相中了Fluid这个开源框架 
做开源本身就是一件为热爱发电的事情 大家都是也是为了了解这里面的技术而加入到这里面来 我在接入Fluid的过程中 也遇到了各种各样的问题 我也会积极的找社区的维护者帮忙解决 也会给社区提pr  
我自己个人写技术公众号来科普Alluxio的时候 也带上了Fluid的安利，这并没有任何人告诉我要这样做 我单纯的就是想分享

至于Star这个事 经常有身边的小伙伴要我帮忙点star 要是我自己写了个不错的东西 我绝对到处分享要star 这样能增加曝光度 让更多的人加入进来 更多的看到这个东西  何况Fluid 已经在很多大厂使用了起来 本身也不缺这个曝光 有参与的贡献者 觉得自己加入的这个社区不错 觉得这个项目不错 想要star 我觉得还正常呀

我觉得还是要正确对待开源 就是因为有各种优秀的开源的项目 才让我们能更快速和方便的实现我们项目 所以遇到好的开源项目 我也会主动去给身边的人分享
