### ISSUE TITLE
[BUG] GitHub stars counter is broken

### ISSUE THREAD

**Issue by kigedooooooooooooooo** [fluid-cloudnative/fluid#1310]
**What is your environment(Kubernetes version, Fluid version, etc.)**
GitHub, web.

**Describe the bug**
Stars count has increased abnormally.

**What you expect to happen:**
Everyone should volunteer to star for a favorite project to support it, and the organization should not ask for stars meaninglessly.

**How to reproduce it**
I hope it is not reproducible.

**Additional Information**
认真说一句，这种行为真的很恶心，我希望它只是一个个人的行为而不是团队的行为，但也请团队引起重视，谢谢保护开源社区环境！

**Comment by cheyang** [comment]
@kigedooooooooooooooo 
您好，我是这个项目的联合创建者、贡献者，也是一名普通的工程师，看到您的issue，我感觉非常心痛。首先向您真诚的道歉，让您产生了困恼，请允许我做一些解释和澄清。这个项目的贡献者来自于不同的公司和高校，没有专业的运营人员，几位项目参与者和社区的小伙伴（全是技术同学）也都是在用自己的业余时间和朋友圈，向可能感兴趣的人宣传和分享这个开源项目及技术。

大家的本意是欢迎更多人了解和支持这个开源技术。我们已经了解清楚，最近有参与社区的伙伴在向身边计算机方向的朋友宣传分享了Fluid项目及技术。宣传消息在层层传播过程中，意思发生了变化，让人产生了误解，从而发生了困扰您的情况。对此我们要特别说明：我们这个项目所有创建者都不能接受任何强迫或暗示别人必须star的行为，任何人都可以unstar或者无视我们的宣传。我们也愿意向对您提出“要求给star”的人做出澄清，如果需要的话可以联系我们。 ** 我们是站在您一边，坚决抵制这种行为!**
我们相信我们正在解决开源社区遇到的一些有意义的技术问题，我们在用自己的业余时间对社区做贡献。如果您注意到，我周末也在贡献这个项目，我把这个项目当成自己的baby，我是充满了热情来维护这个项目，也在花真心在呵护。从我心里我和您一样，不允许它受到玷污。下面，我们会做的事情：

1）我们后续的宣传会更聚焦在Fluid的技术原理上，并且显式说明不接受任何要求star的行为。
2）我们会持续认真把这个开源项目做好，专注于这个开源项目技术本身，也欢迎您参与进来（如果感兴趣的话）。

最后，我代表社区开发者团队认真地说一句：感谢您的反馈，这非常重要。这促使我们认真思考如何来做好开源社区的运营和开源技术的宣传。另外对给您带来的困扰，也向您深深的致歉，以上是我的澄清和思考。
