### ISSUE TITLE
[BUG] the runtime master pod is not restricted to the node where hostpath is located

### ISSUE THREAD

**Issue by iluoeli** [fluid-cloudnative/fluid#141]
**What is your environment(Kubernetes version, Fluid version, etc.)**

**Descirbe the bug**
When I try to accelerate hostpath located on one of my kubernetes cluster nodes, which is a new feature introduced in fluid v0.3.0 ,I have set the correct `nodeAffinity`  in `dataset.yaml` to let fluid know which node my hostpath is on, but it seems that fluid did not use that `nodeAffinity` for runtime master pod, So fluid is likely to create master pod on an unexpedted node, and consequently the pvc created by fluid is empty.

**What you expect to happen:**

**How to reproduce it**

**Additional Information**

**Comment by cheyang** [comment]
@iluoeli I've fixed this issue, please review it. Thanks.

**Comment by iluoeli** [comment]
> @iluoeli I've fixed this issue, please review it. Thanks.

/lgtm. thanks @cheyang

**Comment by cheyang** [comment]
fixed by #130
