### ISSUE TITLE
[DOC] Add doc for Multi-User use same dataset for LocalPath Scenario

### ISSUE THREAD

**Issue by xieydd** [fluid-cloudnative/fluid#148]
**Provide a link to that doc page:**
Have not found. But LocalPath doc [here](https://github.com/fluid-cloudnative/fluid/blob/master/docs/zh/samples/hostpath.md)
**What is the defect and your suggestions on improvement:**
Add a demo for different user(different uid but same gid) use same dataset(only have gid)， i think ot support yet, but not test.

**Comment by TrafalgarZZZ** [comment]
Sorry, I'm actually not sure what you mean "dataset(**only have gid**)", would you explain it with more detail? Maybe with an example to clarify?

**Comment by xieydd** [comment]
Sorry, I misunderstanding the dataset access control.Now i think it is ok for multi-user, process as below:
```
1. admin add user1 and user2 to same group1
2. user1 create dataset1 to cache the data(access control by group1)
2. user2 create dataset2 to cache the data(access control by group1)
```
I will close the issue, if no doubt.

**Comment by TrafalgarZZZ** [comment]
OK. No doubt for me
