### ISSUE TITLE
[DOC] Can fluid visit alluxio web ui?

### ISSUE THREAD

**Issue by edenbuaa** [fluid-cloudnative/fluid#1498]
How to visit alluxio's web page describe here [https://docs.alluxio.io/os/user/stable/en/operation/Web-Interface.html](https://docs.alluxio.io/os/user/stable/en/operation/Web-Interface.html) by fuild?

**Comment by cheyang** [comment]
I think you need to do the following two things:

1. Set the properties of Alluxio runtime `alluxio.web.ui.enabled: true`
2. Use kubectl proxy to access the service of master.

By default, the web access is disabled to reduce overhead. You have the flexibility to enable it by yourself.

**Comment by edenbuaa** [comment]
@cheyang Got it.  thanks.
