### ISSUE TITLE
[FEATURES] Add 'helm lint' to travis for acceptance testing

### ISSUE THREAD

**Issue by cheyang** [fluid-cloudnative/fluid#155]
**What feature you'd like to add:**

Add 'helm lint' to travis for acceptance testing

**Why is this feature needed:**

Because if the charts don't work, the build shouldn't pass.

**Comment by xieydd** [comment]
Does it supported yet?

**Comment by ZhongWeichang001** [comment]
> Does it supported yet?

Not yet :(

**Comment by TrafalgarZZZ** [comment]
Closed by #1384
