### ISSUE TITLE
[BUG] fuse pod can not be created when fluid chart is installed by default in k8s v1.16

### ISSUE THREAD

**Issue by zwwhdls** [fluid-cloudnative/fluid#1573]
**What is your environment(Kubernetes version, Fluid version, etc.)**
k8s: 1.16
fluid: 0.7.0

**Describe the bug**
Fluid chart is installed with critical pod by default. But critical pod can not be created in namespace other than `kube-system`, so  application pod failed with event below: 

```
Events:
  Type     Reason       Age                From               Message
  ----     ------       ----               ----               -------
  Normal   Scheduled    115s               default-scheduler  Successfully assigned default/demo-app to cn-beijing.172.16.0.127
  Warning  FailedMount  23s (x3 over 85s)  kubelet            MountVolume.SetUp failed for volume "default-jfsdemo" : kubernetes.io/csi: mounter.SetupAt failed: rpc error: code = InvalidArgument desc = exit status 1
```

**What you expect to happen:**
Fluid chart can judge whether the critical pod needs to be enabled or not according to the K8s version.

**How to reproduce it**

**Additional Information**

**Comment by qiaoshuangshuang** [comment]
so many bugs.. 目前我们还没解决。

**Comment by liuweibin6566396837** [comment]
have any solution for this issue?
