### ISSUE TITLE
[BUG]The UFS TOTAL SIZE is 0.00B.

### ISSUE THREAD

**Issue by liutingqin** [fluid-cloudnative/fluid#1726]
**What is your environment(Kubernetes version, Fluid version, etc.)**
Kubernetes version:v1.20.0
Fluid version:0.7.0
etc version:3.2.17

**Describe the bug**
在进行了一次加速后，用kubectl delete -f .命令清理了环境，再进行同样操作时，显示UFS的文件大小为0B，alluxio的describe中有warning：Failed to setup ddc engine due to error the UFS is not ready。
另外，想问下，在kubectl delete -f .之后，是不是没有对缓存进行清理，如果没清理，如何清理呢。
![{WIJDRM4H(2MR30)UOT WF9](https://user-images.githubusercontent.com/91254081/161257285-5faf5eb1-65fc-4b0c-970d-a37801a272bd.png)
![77R5TTBIJRW@ G{WMV7HIAP](https://user-images.githubusercontent.com/91254081/161257296-675fb9b4-83ef-4d56-9283-d135c83e0ef4.png)

**What you expect to happen:**

**How to reproduce it**

**Additional Information**

**Comment by cheyang** [comment]
thanks for your interesting of this project. I'm sorry to hear you didn't make it work in get_started.md. Could you follow this guide to gather and upload the logs : https://github.com/fluid-cloudnative/fluid/blob/master/docs/en/userguide/troubleshooting.md

We will help on investigation.

thanks.

**Comment by liutingqin** [comment]
[UFS为0.zip](https://github.com/fluid-cloudnative/fluid/files/8401704/UFS.0.zip)
