### ISSUE TITLE
Can not delete datset and runtime

### ISSUE THREAD

**Issue by ldd91** [fluid-cloudnative/fluid#176]
**What is your environment(Kubernetes version, Fluid version, etc.)**
kubernetes:1.15
Fluid:0.3.0

**Describe the bug**
I deploy dataset and runtime in my cluster,everythong goes well,however 2 day pass,i want to delete all  of them,but it failed,i exec kubectl delete -f dataset.yaml and kubectl delete -f runtime.yaml.
**What you expect to happen:**

**How to reproduce it**

**Additional Information**

**Comment by cheyang** [comment]
能否提供一个脚本工具列出使用指定数据集的pod名字和pod所在的namespace？

**Comment by xieydd** [comment]
Need delete all pod bind with alluxio dataset created pvc.

**Comment by cheyang** [comment]
> Need delete all pod bind with alluxio dataset created pvc.

Only need to delete the running pods, not complete or failed pod
