### ISSUE TITLE
Can you share the paper published on ICDE[DOC]

### ISSUE THREAD

**Issue by yangjunsss** [fluid-cloudnative/fluid#1797]
Can you? Thanks very much, guys.

**Comment by RongGu** [comment]
Hey @yangjunsss , thank you for your interest. The copyright of the paper is transferred to IEEE. We can not make it public until the conference is finished (by May 15th).  After that, we will  add a paper download link on our github readme page. Plus, I will also left a message here. Please stay tuned. Thanks.

**Comment by RongGu** [comment]
It's online now. @yangjunsss https://ieeexplore.ieee.org/document/9835158
