### ISSUE TITLE
[DOC] 提供Non root相关的使用文档

### ISSUE THREAD

**Issue by cheyang** [fluid-cloudnative/fluid#185]
**Provide a link to that doc page:**

**What is the defect and your suggestions on improvement:**

**Comment by TrafalgarZZZ** [comment]
该文档具体指的是[hostpath文档](https://github.com/fluid-cloudnative/fluid/blob/master/docs/zh/samples/hostpath.md)的英文版本吗？还是有关Non-root特性的其他细节？

**Comment by cheyang** [comment]
> 该文档具体指的是[hostpath文档](https://github.com/fluid-cloudnative/fluid/blob/master/docs/zh/samples/hostpath.md)的英文版本吗？还是有关Non-root特性的其他细节？

建议把hostpath和non-root功能分成两个文档。
