### ISSUE TITLE
[FEATURES] 支持Fluid的Pod亲和性调度策略为required

### ISSUE THREAD

**Issue by wpeng2022** [fluid-cloudnative/fluid#1961]
**What feature you'd like to add: 目前调度是best effort，而不是required。

**Why is this feature needed: 希望AI任务只运行在有数据缓存的Node节点。

**Comment by xliuqq** [comment]
@wpeng2022 请问用的是fluid的哪个版本？

**Comment by wpeng2022** [comment]
@xliuqq 0.7.1

**Comment by xliuqq** [comment]
因为fluid 0.7之前的版本对global为false的场景支持不是很好，在fluid 0.7 移除 Runtime 的 FUSE 的global 为 false 的场景，后续会考虑重新支持。

**Comment by xliuqq** [comment]
@wpeng2022 0.7版本只能通过nodeselector进行数据缓存的亲和性调度，见 https://fluid-cloudnative.github.io/zh/samples/data_co_locality.html
