### ISSUE TITLE
Fluid's paper has not been published yet

### ISSUE THREAD

**Issue by KinderRiven** [fluid-cloudnative/fluid#1968]
Hello, can you publish your paper?  ICDE has been finished, but the paper still seems not to be published :(.

**Comment by cheyang** [comment]
Please search https://ieeexplore.ieee.org/Xplore/home.jsp with the topic "Fluid: Dataset Abstraction and Elastic Acceleration for Cloud-native Deep Learning Training Jobs".  I searched, and it's not online yet. We will update this issue once it's  available on the internet. FYI @RongGu

**Comment by RongGu** [comment]
@KinderRiven It's online now. https://ieeexplore.ieee.org/document/9835158 Thanks.
