### ISSUE TITLE
[BUG] Why does Dataset mountPoint  have a limitation min length of 10

### ISSUE THREAD

**Issue by abowloflrf** [fluid-cloudnative/fluid#2000]
Why does Dataset mountPoint have a limitation min length of 10?
What if my data source mount point name is short enough like `mountPoint: pvc://foo` or `mountPoint: s3://foo`

https://github.com/fluid-cloudnative/fluid/blob/e17f96ba384953e5948e2d6878be098e0d866741/api/v1alpha1/dataset_types.go#L70-L74

**Comment by cheyang** [comment]
Thank you for the issue. We set the limitation min length of 10 for most user cases we have. Do you have any suggestions on it?

**Comment by cheyang** [comment]
Ok, you are welcome to contribute the fix. thanks.
