### ISSUE TITLE
[FEATURES]打印版本和commit id

### ISSUE THREAD

**Issue by cheyang** [fluid-cloudnative/fluid#208]
**What feature you'd like to add:**

1.启动dataset controller或者runtime controller的main函数中输出version+commit id，方便问题诊断。

2.或者支持{cli} version

可以借鉴https://github.com/kubeflow/arena/blob/master/cmd/arena/commands/version.go

**Why is this feature needed:**

方便有效诊断问题

**Comment by yangyuliufeng** [comment]
拟支持{cli} version方式查看详细版本信息。
