### ISSUE TITLE
[DOC] README.md picture is Invalid

### ISSUE THREAD

**Issue by zhuyaguang** [fluid-cloudnative/fluid#2131]
**Provide a link to that doc page:**  https://github.com/fluid-cloudnative/fluid

**What is the defect and your suggestions on improvement:**

click the picture is response

`Invalid upstream response (403)
`

<img width="557" alt="image" src="https://user-images.githubusercontent.com/8857976/190118792-5868fce9-5d04-481e-84a2-1c4b88983f68.png">

**Comment by TrafalgarZZZ** [comment]
Thanks for informing! I think we may use an embedded static resource to avoid this. @wang-mask
