### ISSUE TITLE
[BUG]Driver name not found in the list of registered CSI drivers

### ISSUE THREAD

**Issue by valiantljk** [fluid-cloudnative/fluid#214]
**What is your environment(Kubernetes version, Fluid version, etc.)**
K8S: 1.14
**Describe the bug**
When creating a demo app following this example: https://github.com/fluid-cloudnative/fluid/blob/master/docs/en/samples/accelerate_data_accessing.md

Pod/nginx stuck in pending status. The alluxio-master log shows:

```
Warning  FailedMount  10m (x45 over 85m)    kubelet, 10.147.160.77  MountVolume.MountDevice failed for volume "hbase" : driver name fuse.csi.fluid.io not found in the list of registered CSI drivers
  Warning  FailedMount  5m26s (x39 over 83m)  kubelet, 10.147.160.77  Unable to mount volumes for pod "nginx_default(bda07d70-0846-11eb-ba61-b8599fb51ea8)": timeout expired waiting for volumes to attach or mount for pod "default"/"nginx". list of unmounted volumes=[hbase-vol]. list of unattached volumes=[hbase-vol default-token-ntghn]
```

The csidriver:

```
kubectl get csidriver
NAME                                  CREATED AT
fuse.csi.fluid.io                     2020-10-06T04:15:14Z
kubectl  logs csidriver/fuse.csi.fluid.io
error: cannot get the logs from *v1beta1.CSIDriver: selector for *v1beta1.CSIDriver not implemented
```

The csi-plugin on the same node with the pod/nginx: 

```
kubectl logs pod/csi-nodeplugin-fluid-j4dkl -n fluid-system -c plugins
I1006 12:15:22.749832 2304931 driver.go:56] Driver: fuse.csi.fluid.io version: 1.0.0
I1006 12:15:22.749906 2304931 driver.go:59] protocol: unix addr: var/lib/kubelet/csi-plugins/fuse.csi.fluid.io/csi.sock
I1006 12:15:22.749975 2304931 driver.go:81] Enabling controller service capability: CREATE_DELETE_VOLUME
I1006 12:15:22.749981 2304931 driver.go:93] Enabling volume access mode: MULTI_NODE_MULTI_WRITER
I1006 12:15:22.750115 2304931 server.go:108] Listening for connections on address: &net.UnixAddr{Name:"/var/lib/kubelet/csi-plugins/fuse.csi.fluid.io/csi.sock", Net:"unix"}
I1006 12:15:23.430501 2304931 utils.go:97] GRPC call: /csi.v1.Identity/GetPluginInfo
I1006 12:15:23.430518 2304931 utils.go:98] GRPC request: {}
I1006 12:15:23.431200 2304931 identityserver-default.go:32] Using default GetPluginInfo
I1006 12:15:23.431205 2304931 utils.go:103] GRPC response: {"name":"fuse.csi.fluid.io","vendor_version":"1.0.0"}
```

```
kubectl logs pod/csi-nodeplugin-fluid-j4dkl -n fluid-system -c node-driver-registrar

I1006 04:15:16.117383 2303707 main.go:110] Version: v1.2.0-0-g6ef000ae
I1006 04:15:16.117427 2303707 main.go:120] Attempting to open a gRPC connection with: "/var/lib/kubelet/csi-plugins/fuse.csi.fluid.io/csi.sock"
I1006 04:15:16.117437 2303707 connection.go:151] Connecting to unix:///var/lib/kubelet/csi-plugins/fuse.csi.fluid.io/csi.sock
I1006 04:15:23.422345 2303707 main.go:127] Calling CSI driver to discover driver name
I1006 04:15:23.422362 2303707 connection.go:180] GRPC call: /csi.v1.Identity/GetPluginInfo
I1006 04:15:23.422366 2303707 connection.go:181] GRPC request: {}
I1006 04:15:23.431780 2303707 connection.go:183] GRPC response: {"name":"fuse.csi.fluid.io","vendor_version":"1.0.0"}
I1006 04:15:23.432206 2303707 connection.go:184] GRPC error: <nil>
I1006 04:15:23.432212 2303707 main.go:137] CSI driver name: "fuse.csi.fluid.io"
I1006 04:15:23.432232 2303707 node_register.go:58] Starting Registration Server at: /registration/fuse.csi.fluid.io-reg.sock
I1006 04:15:23.432319 2303707 node_register.go:67] Registration Server started at: /registration/fuse.csi.fluid.io-reg.sock
```

**What you expect to happen:**
Demo app could run
**How to reproduce it**
Following example at https://github.com/fluid-cloudnative/fluid/blob/master/docs/en/samples/accelerate_data_accessing.md
**Additional Information**

**Comment by cheyang** [comment]
Could you try to use https://github.com/fluid-cloudnative/fluid/blob/master/tools/diagnose-fluid.sh which is the latest version? I tried this, it can work fine.

```
./diagnose-fluid.sh collect --name hbase
Start collecting, runtime-name=hbase, runtime-namespace=default
tar: 从成员名中删除开头的“/”
/tmp/diagnose_fluid_1602052804/
/tmp/diagnose_fluid_1602052804/pods-fluid-system/
/tmp/diagnose_fluid_1602052804/pods-fluid-system/csi-nodeplugin-fluid-w96r4-node-driver-registrar.log
/tmp/diagnose_fluid_1602052804/pods-fluid-system/csi-nodeplugin-fluid-gl4qw-plugins.log
/tmp/diagnose_fluid_1602052804/pods-fluid-system/csi-nodeplugin-fluid-hjkwj-plugins.log
/tmp/diagnose_fluid_1602052804/pods-fluid-system/csi-nodeplugin-fluid-t9qrl-plugins.log
/tmp/diagnose_fluid_1602052804/pods-fluid-system/csi-nodeplugin-fluid-w96r4-plugins.log
/tmp/diagnose_fluid_1602052804/pods-fluid-system/controller-manager-9b84f87b9-k59zd-manager.log
/tmp/diagnose_fluid_1602052804/pods-fluid-system/csi-nodeplugin-fluid-hjkwj-node-driver-registrar.log
/tmp/diagnose_fluid_1602052804/pods-fluid-system/csi-nodeplugin-fluid-gl4qw-node-driver-registrar.log
/tmp/diagnose_fluid_1602052804/pods-fluid-system/csi-nodeplugin-fluid-t9qrl-node-driver-registrar.log
/tmp/diagnose_fluid_1602052804/fluid-system.log
/tmp/diagnose_fluid_1602052804/default.log
/tmp/diagnose_fluid_1602052804/hbase.yaml
/tmp/diagnose_fluid_1602052804/pods-default/
/tmp/diagnose_fluid_1602052804/pods-default/hbase-worker-64xks-alluxio-job-worker.log
/tmp/diagnose_fluid_1602052804/pods-default/hbase-fuse-bh8gj-alluxio-fuse.log
/tmp/diagnose_fluid_1602052804/pods-default/hbase-worker-97dsz-alluxio-worker.log
/tmp/diagnose_fluid_1602052804/pods-default/hbase-fuse-fm588-alluxio-fuse.log
/tmp/diagnose_fluid_1602052804/pods-default/hbase-master-0-alluxio-master.log
/tmp/diagnose_fluid_1602052804/pods-default/hbase-worker-97dsz-alluxio-job-worker.log
/tmp/diagnose_fluid_1602052804/pods-default/hbase-worker-64xks-alluxio-worker.log
/tmp/diagnose_fluid_1602052804/pods-default/hbase-master-0-alluxio-job-master.log
/tmp/diagnose_fluid_1602052804/fluid.yaml
please get diagnose_fluid_1602052804.tar.gz for diagnostics
```


And could you also collect the runtime and dataset status by using

```
kubectl get dataset -oyaml
kubectl get alluxioruntime -oyaml
```

**Comment by valiantljk** [comment]
1. diagnose_fluid.sh still not working for me. Same error:
`./diagnose-fluid1.sh collect --name hbase`
`getopt: illegal option -- o
`
2. 
`kubectl get dataset hbase -oyaml`

`apiVersion: data.fluid.io/v1alpha1
kind: Dataset
metadata:
  creationTimestamp: "2020-10-07T02:26:12Z"
  finalizers:
  - fluid-dataset-controller-finalizer
  generation: 1
  name: hbase
  namespace: default
  resourceVersion: "33068650"
  selfLink: /apis/data.fluid.io/v1alpha1/namespaces/default/datasets/hbase
  uid: 77dc3e07-0844-11eb-ba61-b8599fb51ea8
spec:
  mounts:
  - mountPoint: https://mirrors.tuna.tsinghua.edu.cn/apache/hbase/2.2.5/
    name: hbase
status:
  cacheStates:
    cacheCapacity: 4GiB
    cached: 0B
    cachedPercentage: 0%
  conditions:
  - lastTransitionTime: "2020-10-07T02:30:09Z"
    lastUpdateTime: "2020-10-07T16:37:39Z"
    message: The ddc runtime is ready.
    reason: DatasetReady
    status: "True"
    type: Ready
  phase: Bound
  runtimes:
  - category: Accelerate
    name: hbase
    namespace: default
    type: alluxio
  ufsTotal: 443.5MiB`

`kubectl get alluxioruntime hbase -oyaml`

`apiVersion: data.fluid.io/v1alpha1
kind: AlluxioRuntime
metadata:
  creationTimestamp: "2020-10-07T02:27:54Z"
  finalizers:
  - alluxio-runtime-controller-finalizer
  generation: 2
  name: hbase
  namespace: default
  resourceVersion: "32632526"
  selfLink: /apis/data.fluid.io/v1alpha1/namespaces/default/alluxioruntimes/hbase
  uid: b4436b0b-0844-11eb-ba61-b8599fb51ea8
spec:
  alluxioVersion: {}
  data:
    pin: false
    replicas: 0
  fuse:
    args:
    - fuse
    - --fuse-opts=kernel_cache,ro,max_read=131072,attr_timeout=7200,entry_timeout=7200,nonempty,max_readahead=0
    resources: {}
  initUsers:
    resources: {}
  jobMaster:
    resources: {}
  jobWorker:
    resources: {}
  master:
    resources: {}
  properties:
    alluxio.user.block.size.bytes.default: 256MB
    alluxio.user.local.reader.chunk.size.bytes: 256MB
    alluxio.user.streaming.data.timeout: 300sec
    alluxio.user.streaming.reader.chunk.size.bytes: 256MB
    alluxio.worker.network.reader.buffer.size: 256MB
  replicas: 2
  tieredstore:
    levels:
    - high: "0.95"
      low: "0.7"
      mediumtype: MEM
      path: /dev/shm
      quota: 2Gi
  worker:
    resources: {}
status:
  cacheStates:
    cacheCapacity: 4GiB
    cached: 0B
    cachedPercentage: 0%
  conditions:
  - lastProbeTime: "2020-10-07T02:28:20Z"
    lastTransitionTime: "2020-10-07T02:28:20Z"
    message: The master is initialized.
    reason: Master is initialized
    status: "True"
    type: MasterInitialized
  - lastProbeTime: "2020-10-07T02:28:53Z"
    lastTransitionTime: "2020-10-07T02:28:20Z"
    message: The master is ready.
    reason: Master is ready
    status: "True"
    type: MasterReady
  - lastProbeTime: "2020-10-07T02:28:33Z"
    lastTransitionTime: "2020-10-07T02:28:33Z"
    message: The workers are initialized.
    reason: Workers are initialized
    status: "True"
    type: WorkersInitialized
  - lastProbeTime: "2020-10-07T02:28:33Z"
    lastTransitionTime: "2020-10-07T02:28:33Z"
    message: The fuses are initialized.
    reason: Fuses are initialized
    status: "True"
    type: FusesInitialized
  - lastProbeTime: "2020-10-07T02:28:53Z"
    lastTransitionTime: "2020-10-07T02:28:53Z"
    message: The workers are partially ready.
    reason: Workers are ready
    status: "True"
    type: WorkersReady
  - lastProbeTime: "2020-10-07T02:28:53Z"
    lastTransitionTime: "2020-10-07T02:28:53Z"
    message: The fuses are partially ready.
    reason: Fuses are ready
    status: "True"
    type: FusesReady
  currentFuseNumberScheduled: 2
  currentMasterNumberScheduled: 1
  currentWorkerNumberScheduled: 2
  desiredFuseNumberScheduled: 2
  desiredMasterNumberScheduled: 1
  desiredWorkerNumberScheduled: 2
  fuseNumberAvailable: 2
  fuseNumberReady: 2
  fusePhase: Ready
  masterNumberReady: 1
  masterPhase: Ready
  valueFile: hbase-alluxio-values
  workerNumberAvailable: 2
  workerNumberReady: 2
  workerPhase: Ready`

3. will upload kubelet logs later

No, I didn't use Helm to install, I used helm template to convert everything into one yaml, and used kubectl to deploy fuild.

**Comment by cheyang** [comment]
For diagnose script, I think the reason is that there are some illegal characters. like https://blog.csdn.net/qq_43075039/article/details/98475964

Could you try download by using

```
wget https://raw.githubusercontent.com/fluid-cloudnative/fluid/master/tools/diagnose-fluid.sh
```

**Comment by cheyang** [comment]
> > diagnose_fluid.sh still not working for me. Same error:
> > ./diagnose-fluid1.sh collect --name hbase
> > getopt: illegal option -- o
> 
> For diagnose script, I think the reason is that there are some illegal characters. like https://blog.csdn.net/qq_43075039/article/details/98475964
> 
> Could you try to download the script by using
> 
> ```
> wget https://raw.githubusercontent.com/fluid-cloudnative/fluid/master/tools/diagnose-fluid.sh
> ```

> No, I didn't use Helm to install, I used helm template to convert everything into one yaml, and used kubectl to deploy fuild.

we recommend to use helm, because it's good for managing the lifecycle and the diagnose tool are based on assumption of the deployment of fluid comments is helm.

**Comment by fredkan** [comment]
> **What is your environment(Kubernetes version, Fluid version, etc.)**
> K8S: 1.14
> **Describe the bug**
> When creating a demo app following this example: https://github.com/fluid-cloudnative/fluid/blob/master/docs/en/samples/accelerate_data_accessing.md
> 
> Pod/nginx stuck in pending status. The alluxio-master log shows:
> 
> ```
> Warning  FailedMount  10m (x45 over 85m)    kubelet, 10.147.160.77  MountVolume.MountDevice failed for volume "hbase" : driver name fuse.csi.fluid.io not found in the list of registered CSI drivers
>   Warning  FailedMount  5m26s (x39 over 83m)  kubelet, 10.147.160.77  Unable to mount volumes for pod "nginx_default(bda07d70-0846-11eb-ba61-b8599fb51ea8)": timeout expired waiting for volumes to attach or mount for pod "default"/"nginx". list of unmounted volumes=[hbase-vol]. list of unattached volumes=[hbase-vol default-token-ntghn]
> ```
> 
> The csidriver:
> 
> ```
> kubectl get csidriver
> NAME                                  CREATED AT
> fuse.csi.fluid.io                     2020-10-06T04:15:14Z
> kubectl  logs csidriver/fuse.csi.fluid.io
> error: cannot get the logs from *v1beta1.CSIDriver: selector for *v1beta1.CSIDriver not implemented
> ```
> 
> The csi-plugin on the same node with the pod/nginx:
> 
> ```
> kubectl logs pod/csi-nodeplugin-fluid-j4dkl -n fluid-system -c plugins
> I1006 12:15:22.749832 2304931 driver.go:56] Driver: fuse.csi.fluid.io version: 1.0.0
> I1006 12:15:22.749906 2304931 driver.go:59] protocol: unix addr: var/lib/kubelet/csi-plugins/fuse.csi.fluid.io/csi.sock
> I1006 12:15:22.749975 2304931 driver.go:81] Enabling controller service capability: CREATE_DELETE_VOLUME
> I1006 12:15:22.749981 2304931 driver.go:93] Enabling volume access mode: MULTI_NODE_MULTI_WRITER
> I1006 12:15:22.750115 2304931 server.go:108] Listening for connections on address: &net.UnixAddr{Name:"/var/lib/kubelet/csi-plugins/fuse.csi.fluid.io/csi.sock", Net:"unix"}
> I1006 12:15:23.430501 2304931 utils.go:97] GRPC call: /csi.v1.Identity/GetPluginInfo
> I1006 12:15:23.430518 2304931 utils.go:98] GRPC request: {}
> I1006 12:15:23.431200 2304931 identityserver-default.go:32] Using default GetPluginInfo
> I1006 12:15:23.431205 2304931 utils.go:103] GRPC response: {"name":"fuse.csi.fluid.io","vendor_version":"1.0.0"}
> ```
> 
> ```
> kubectl logs pod/csi-nodeplugin-fluid-j4dkl -n fluid-system -c node-driver-registrar
> 
> I1006 04:15:16.117383 2303707 main.go:110] Version: v1.2.0-0-g6ef000ae
> I1006 04:15:16.117427 2303707 main.go:120] Attempting to open a gRPC connection with: "/var/lib/kubelet/csi-plugins/fuse.csi.fluid.io/csi.sock"
> I1006 04:15:16.117437 2303707 connection.go:151] Connecting to unix:///var/lib/kubelet/csi-plugins/fuse.csi.fluid.io/csi.sock
> I1006 04:15:23.422345 2303707 main.go:127] Calling CSI driver to discover driver name
> I1006 04:15:23.422362 2303707 connection.go:180] GRPC call: /csi.v1.Identity/GetPluginInfo
> I1006 04:15:23.422366 2303707 connection.go:181] GRPC request: {}
> I1006 04:15:23.431780 2303707 connection.go:183] GRPC response: {"name":"fuse.csi.fluid.io","vendor_version":"1.0.0"}
> I1006 04:15:23.432206 2303707 connection.go:184] GRPC error: <nil>
> I1006 04:15:23.432212 2303707 main.go:137] CSI driver name: "fuse.csi.fluid.io"
> I1006 04:15:23.432232 2303707 node_register.go:58] Starting Registration Server at: /registration/fuse.csi.fluid.io-reg.sock
> I1006 04:15:23.432319 2303707 node_register.go:67] Registration Server started at: /registration/fuse.csi.fluid.io-reg.sock
> ```
> 
> **What you expect to happen:**
> Demo app could run
> **How to reproduce it**
> Following example at https://github.com/fluid-cloudnative/fluid/blob/master/docs/en/samples/accelerate_data_accessing.md
> **Additional Information**

Could you please provide the node logs of the error pod;
/var/log/messages

**Comment by valiantljk** [comment]
Here is /var/log/messages:

root@n147-160-077:~# cat /var/log/messages
Oct  4 06:25:01 n147-160-077 liblogging-stdlog:  [origin software="rsyslogd" swVersion="8.24.0" x-pid="5656" x-info="http://www.rsyslog.com"] rsyslogd was HUPed


For the kubelet.log, it's a 1.8G file, I have no idea which to look for, could you give me some hint? @cheyang @fredkan

**Comment by cheyang** [comment]
I think the logging of common CSI is not  so good, It just show there is an error, but the error is <nil> . you can check the source code of logging: https://github.com/kubernetes-csi/drivers/blob/master/pkg/csi-common/utils.go#L97-L105

```
I1006 04:15:23.422345 2303707 main.go:127] Calling CSI driver to discover driver name
I1006 04:15:23.422362 2303707 connection.go:180] GRPC call: /csi.v1.Identity/GetPluginInfo
I1006 04:15:23.422366 2303707 connection.go:181] GRPC request: {}
I1006 04:15:23.431780 2303707 connection.go:183] GRPC response: {"name":"fuse.csi.fluid.io","vendor_version":"1.0.0"}
I1006 04:15:23.432206 2303707 connection.go:184] GRPC error: <nil>
```

So I do some enhancement in the this PR: https://github.com/fluid-cloudnative/fluid/pull/221/files#diff-fd5c9704d91d666649fa10e53f1deaf8R102-R103, especially in https://github.com/fluid-cloudnative/fluid/blob/9aabaeb34283fcf3555d4e176075df663287fde7/vendor/github.com/kubernetes-csi/drivers/pkg/csi-common/utils.go#L101-L106 . You can update the docker image of csi-plugin to registry.cn-hangzhou.aliyuncs.com/fluid/fluid-csi:v0.4.0-1083b6a. And check the logs again.

And from the kubelet log, you can search something like below. But it works fine

```
10月 09 18:49:19 iZ2ze0pget2kzaquo2thb5Z kubelet[2638]: I1009 18:49:19.571550    2638 csi_plugin.go:101] kubernetes.io/csi: Trying to validate a new CSI Driver with name: fuse.csi.fluid.io endpoint: /var/lib/kubelet/csi-plugins/fuse.csi.fluid.io/csi.sock versions: 1.0.0, foundInDeprecatedDir: false
10月 09 18:49:19 iZ2ze0pget2kzaquo2thb5Z kubelet[2638]: I1009 18:49:19.571595    2638 csi_plugin.go:120] kubernetes.io/csi: Register new plugin with name: fuse.csi.fluid.io at endpoint: /var/lib/kubelet/csi-plugins/fuse.csi.fluid.io/csi.sock
```

**Comment by cheyang** [comment]
I suggest you should take a look at the kubelet log which has csi_plugin.go 

```
grep csi_plugin.go kubelet.log 
```

And you can also check the issue: /github.com/kubernetes/kubernetes/issues/68688

**Comment by xieydd** [comment]
@valiantljk The node’s kubelet root_dir is `/var/lib/kubelet`?

**Comment by nparekh-futurewei** [comment]
Any update on this? Why is this closed? The older issue 68688 was not resolving this error while deploying an alluxio trial nginix pod.
