### ISSUE TITLE
[BUG]fuse.csi.fluid.io not found in the list registered CSI drivers when node restart in k8s 1.15.1

### ISSUE THREAD

**Issue by ldd91** [fluid-cloudnative/fluid#220]
**What is your environment(Kubernetes version, Fluid version, etc.)**
kubernetes:v1.15
fluid:0.3.0

**Describe the bug**
I deploy runtime and dataset in node1,everything goes well.when i restart node1,runtime and dataset is running,csi-nodeplugin-fluid-xxx is also running,when i deploy a pod in this node,the pod log shows MountVolume.MountDevice failed for volume "zj-lmdb" : driver name fuse.csi.fluid.io not found in the list registered CSI drivers 

**What you expect to happen:**

**How to reproduce it**
restart the runtime node
**Additional Information**

**Comment by ldd91** [comment]
![Uploading plugin日志sci.JPG…]()

**Comment by ldd91** [comment]
![plguin日志](https://user-images.githubusercontent.com/29392150/95571679-6784f300-0a5b-11eb-95b2-7be77712483f.jpg)
![plugin日志sci](https://user-images.githubusercontent.com/29392150/95571691-6a7fe380-0a5b-11eb-951a-da22939856a0.JPG)

**Comment by ldd91** [comment]
![111](https://user-images.githubusercontent.com/29392150/95572140-1fb29b80-0a5c-11eb-95f7-70950c52a787.png)
![222](https://user-images.githubusercontent.com/29392150/95572146-2214f580-0a5c-11eb-9a40-c01bc7d40937.png)

**Comment by cheyang** [comment]
I suggest you should take a look at the kubelet log which has csi_plugin.go 

```
grep csi_plugin.go kubelet.log 
```

And you can also check the issue: /github.com/kubernetes/kubernetes/issues/68688

**Comment by cheyang** [comment]
Could you run the following commands?

```
kubectl get csidrivers
kubectl describe csidrivers fuse.csi.fluid.io
```


The output I got


```
[root@iZ2ze0pget2kzaquo2thb5Z pods-fluid-system]# kubectl describe csidrivers fuse.csi.fluid.io
Name:         fuse.csi.fluid.io
Namespace:
Labels:       <none>
Annotations:  <none>
API Version:  storage.k8s.io/v1beta1
Kind:         CSIDriver
Metadata:
  Creation Timestamp:  2020-10-09T23:50:53Z
  Resource Version:    21817966
  Self Link:           /apis/storage.k8s.io/v1beta1/csidrivers/fuse.csi.fluid.io
  UID:                 8dea13aa-6ae4-4a48-8098-26b5b52a50ea
Spec:
  Attach Required:    false
  Pod Info On Mount:  true
  Volume Lifecycle Modes:
    Persistent
Events:  <none>
```
