### ISSUE TITLE
[BUG] unexpected worker pods were produced when fuse-only enabled.

### ISSUE THREAD

**Issue by SimonCqk** [fluid-cloudnative/fluid#2203]
**What is your environment(Kubernetes version, Fluid version, etc.)**

fluid >= release-v0.8

**Describe the bug**

When I create a pair of DataSet & JindoRuntime and enable fuse-only mode, it seems that worker pods are still created, which is unexpected.
![image](https://user-images.githubusercontent.com/19202395/196617529-e80b82a8-1b13-4c34-a5b3-a625677c83c5.png)

![image](https://user-images.githubusercontent.com/19202395/196617709-d71a1705-757b-48d5-a8f6-7c83187aae40.png)

**What you expect to happen:**

There should be only fuse-pods when fuse-only mode enabled.

**How to reproduce it**

**Additional Information**

**Comment by frankleaf** [comment]
apiVersion: data.fluid.io/v1alpha1
kind: JindoRuntime
metadata:
  name: hadoop
spec:
  master:
    disabled: true
  worker:
    disabled: true

replicas and tieredstore not need
