### ISSUE TITLE
[BUG] MountVolume.SetUp failed for volume "fluid-src-dir" : mkdir /alluxio-mnt: read-only file system

### ISSUE THREAD

**Issue by valiantljk** [fluid-cloudnative/fluid#222]
**What is your environment(Kubernetes version, Fluid version, etc.)**
Kubernetes: 1.15
Fluid: 0.3.0
Helm: v3
**Describe the bug**
Followed instructions at [here](https://github.com/fluid-cloudnative/fluid/blob/master/docs/zh/userguide/get_started.md) 
Trying to install fluid with Helm3 on GKE. Found that PODS in fluid-system stuck in 'container creating' status. Only controller-manager pod runs well. Here is the log:
`kubectl describe pod/csi-nodeplugin-fluid-6dsff -n fluid-system 
MountVolume.SetUp failed for volume "fluid-src-dir" : mkdir /alluxio-mnt: read-only file system`

After changing the csi-nodeplugin-fluid daemonset.yaml by specifying the MountVolume as readOnly: False, 
still not working. 
**What you expect to happen:**
Fluid can be deployed on GKE
**How to reproduce it**

Helm install fluid fluid/

**Additional Information**

**Comment by cheyang** [comment]
Can you run `mkdir /alluxio-mnt` in the k8s node? 

You can use the follow command to check the node info.

```
kubectl get po -n fluid-system -o wide
```

**Comment by cheyang** [comment]
Does GKE's kubelet has authority to create directory in k8s node?

**Comment by valiantljk** [comment]
It looks like [GKE](https://cloud.google.com/container-optimized-os/docs/concepts/disks-and-filesystem) node's root file system is read only. 

Does alluxio-mnt has to be in root / ?

**Comment by cheyang** [comment]
I've fixed it in https://github.com/fluid-cloudnative/fluid/pull/223. And please delete the existing chart and  install with the chart: https://github.com/fluid-cloudnative/fluid/blob/fb123c104c4e0d8707260fcbb2b6de32f868054a/charts/fluid/fluid/values.yaml

**Comment by cheyang** [comment]
And please follow the updated guide: https://github.com/fluid-cloudnative/fluid/blob/master/docs/zh/samples/accelerate_data_accessing.md

And notice:

```
注意: 上述mountPoint中使用了Apache清华镜像源进行演示，如果你的环境位于海外，请更换为https://downloads.apache.org/hbase/2.2.5/进行尝试
```
