### ISSUE TITLE
[BUG] set Port Properties In alluxioRuntime, alluxio Pod crash

### ISSUE THREAD

**Issue by hahchenchen** [fluid-cloudnative/fluid#2262]
**What is your environment(Kubernetes version, Fluid version, etc.)**
fluid: 0.8.0
alluxio: 2.8.1
k8s: 1.18
**Describe the bug**
when set the port Properties In alluxioRuntime. the alluxio pod crash.

port Properties In alluxioRuntime:
![image](https://user-images.githubusercontent.com/22194004/199498635-a1f5712f-6f98-46b5-80b8-a101e4d7abdd.png)

the alluxio master sts yaml
![image](https://user-images.githubusercontent.com/22194004/199498507-3789c07e-9645-40e2-8823-420f8954228a.png)

the alluxio helm value configmap
![image](https://user-images.githubusercontent.com/22194004/199498817-c3785c2d-06ff-4e91-8a6b-df36f7073bfc.png)

**What you expect to happen:**
the port Properties setted in alluxio master worker yaml. also setted in alluxio java opts.

**How to reproduce it**

runtime yaml:
...
spec:
  properties:
    alluxio.master.rpc.port: "20118"
    alluxio.master.web.port: "22313"
    alluxio.master.embedded.journal.port: "20497"
    alluxio.job.master.rpc.port: "23657"
    alluxio.job.master.web.port: "23703"
    alluxio.job.master.embedded.journal.port: "25776"
    alluxio.worker.rpc.port: "20105"
    alluxio.worker.web.port: "23217"
    alluxio.job.worker.rpc.port: "24803"
    alluxio.job.worker.data.port: "24654"
    alluxio.job.worker.web.port: "22429"
...

**Additional Information**

**Comment by hahchenchen** [comment]
I aready found the reason, the port Properties do not set in alluxio yaml. but set in alluxio java opts.
the port is not match.

I will send a pr to fix it.

**Comment by cheyang** [comment]
fixed by #2263
