### ISSUE TITLE
[BUG] set tieredstore in AlluxioRuntime do not affect memory request.

### ISSUE THREAD

**Issue by hahchenchen** [fluid-cloudnative/fluid#2294]
**What is your environment(Kubernetes version, Fluid version, etc.)**
k8s: 1.18
fluid: 0.8.0
alluxio: 2.8.1

**Describe the bug**
1、set tieredstore in AlluxioRuntime do not affect memory request.
2、only set memory reqeust, do not take affect.
![ff82a68e58a939022044a40280976031d2b39084](https://user-images.githubusercontent.com/22194004/200987533-049c34a9-34d9-4525-8d60-156d12db3d03.png)
![498b21cb4d4351f4f351a20df7751f2c8b978cee](https://user-images.githubusercontent.com/22194004/200987540-0f5c092c-1266-4f87-add0-4ecee4c0bdb6.png)

**What you expect to happen:**
1、when set tieredstore in AlluxioRuntime , the worker memory request will be added.
2、when only set memory reqeust, will take affect.
**How to reproduce it**

**Additional Information**

**Comment by TrafalgarZZZ** [comment]
fixed by #2295
