### ISSUE TITLE
[BUG]set dataset mount.path of local/pvc , do no take effect. the container path still use mount.name

### ISSUE THREAD

**Issue by hahchenchen** [fluid-cloudnative/fluid#2405]
**What is your environment(Kubernetes version, Fluid version, etc.)**
fluid master
**Describe the bug**
when set the dataset mount.path of fluid native(local/pvc), the path do no take effect. the sts mountpoint container path still use mount.name.
this is different with the dataset  of ufs. 
**What you expect to happen:**
when set the dataset mount.path of fluid native(local/pvc), the path should take effect. the sts mountpoint container path should use the path.

when the mount path do not set, then use the mount.name.
**How to reproduce it**

**Additional Information**

**Comment by TrafalgarZZZ** [comment]
Closed by #2406
