### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by kids12138** [fluid-cloudnative/fluid#2582]
csi-node plugin-fluid  Pod failed to start ，I am using the latest master branch，One of the container plugins in the pod failed to start，
the tips is : No such file or directory

**Comment by kids12138** [comment]
![image](https://user-images.githubusercontent.com/41765539/218243176-5db9c400-0323-4cdc-8fa5-d95d5df56840.png)

**Comment by kids12138** [comment]
container description 
![image](https://user-images.githubusercontent.com/41765539/218243201-7c9504c4-31ac-47d8-8cb4-87d751a707d7.png)
My  csi dockerfile is  
![image](https://user-images.githubusercontent.com/41765539/218243249-5a917517-79bf-4f6a-a1e9-9e340afad893.png)

**Comment by cheyang** [comment]
Sorry, I am not able to reproduce the issue with latest build: v0.9.0-fcf2004. 
![image](https://user-images.githubusercontent.com/3724388/218251770-c32421d5-6e98-4269-819e-550c506e9c14.png)


From the error in your snapshot, I  think you didn't use the latest version in master branch. At least, I didn't see the same args in your environment. Could you please check?

**Comment by kids12138** [comment]
![image](https://user-images.githubusercontent.com/41765539/218297337-5958761a-0bde-46d5-8229-f2249b417b16.png)
Failed to build csi image ，how to solve

**Comment by cheyang** [comment]
Seems that you need docker login before building docker image.

**Comment by kids12138** [comment]
![image](https://user-images.githubusercontent.com/41765539/218412657-73862e4c-e0d5-4596-8209-087754d5c144.png)
After I retested, I found that only one csi is working normally, is this status correct

**Comment by kids12138** [comment]
I found the reason, thank you
