### ISSUE TITLE
[BUG] Not able to pull csi registrar docker image

### ISSUE THREAD

**Issue by Sharathmk99** [fluid-cloudnative/fluid#2750]
**What is your environment(Kubernetes version, Fluid version, etc.)**
Kubernetes version: 1.20.x

**Describe the bug**
Not able to pull docker image `registry.aliyuncs.com/acs/csi-node-driver-registrar:v2.3.0-038aeb6-aliyun`

**What you expect to happen:**
Should be able to pull registrar docker image

**How to reproduce it**
`dokcer pull registry.aliyuncs.com/acs/csi-node-driver-registrar:v2.3.0-038aeb6-aliyun`

**Additional Information**
Error,
```
Error response from daemon: Get https://registry.aliyuncs.com/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
```

**Comment by TrafalgarZZZ** [comment]
@Sharathmk99 
Pls try with this image `k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.3.0`.

Found in https://github.com/kubernetes-csi/node-driver-registrar

**Comment by cheyang** [comment]
@Sharathmk99 you can use `fluidcloudnative/csi-node-driver-registrar:v2.3.0` now.
