### ISSUE TITLE
[FEATURES] Support for generating idempotent Alluxio mount commands as a secret or config in Fluid

### ISSUE THREAD

**Issue by cheyang** [fluid-cloudnative/fluid#2771]
**What feature you'd like to add:**

Currently, when deploying a dataset based on Alluxio using Fluid, the mount command is run during the setup process and will not be executed again if the Alluxio master node is scheduled to a different node. To address this issue, we propose adding support for generating idempotent Alluxio mount commands as a secret or config in Fluid, mounting it in the Alluxio master pod, and running it as a post-start script.

This would allow users to store the Alluxio mount commands securely and enable them to be executed even if the master node is rescheduled. Additionally, this would simplify the process of setting up Alluxio-based datasets in Fluid.

It's important that the generated script is idempotent to avoid issues with data consistency and performance. This means that the script should be designed to be executed multiple times without changing the end result after the first execution.

**Why is this feature needed:**

**Comment by wang-mask** [comment]
The master mount data by command line in yaml. In my case, after the master is scheduled to a different node, the master can alse execute the command to mount data.
