### ISSUE TITLE
[FEATURES] How to customize labels for pvc created by runtime?

### ISSUE THREAD

**Issue by weixiao-huang** [fluid-cloudnative/fluid#2775]
**What feature you'd like to add:**

Sometimes we might add some custom labels to pvc created by runtime. Now I notice in `AlluxioRuntime`, there're `spec.fuse.podMetadata`, `spec.master.podMetadata`, `spec.worker.podMetadata` to specify labels for pod. But where could I add custom labels to pvc?

**Why is this feature needed:**

In our internal platform, we add some labels like `creator-id` and `creator` in pvc for checking who creates this pvc. So specifying custom pvc labels may be necessary

**Comment by cheyang** [comment]
What about `spec.pvcMetadata` ?

**Comment by weixiao-huang** [comment]
> What about `spec.pvcMetadata` ?

Great, I'll try to write a PR to use `spec.pvcMetadata`

**Comment by TrafalgarZZZ** [comment]
Probably there may be another use case where we need something like `pvMetadata`?
