### ISSUE TITLE
Remediation tip: pin your Docker image by updating alpine to fixed version

### ISSUE THREAD

**Issue by cheyang** [fluid-cloudnative/fluid#2827]
Remediation tip: pin your Docker image by updating alpine to alpine@sha256:124c7d2707904eea7431fffe91522a01e5a861a624ee31d03372cc1d138a3126

@baowj-678 

Tracking issue for:
- [ ] https://github.com/fluid-cloudnative/fluid/security/code-scanning/144

**Comment by baowj-678** [comment]
This pr https://github.com/fluid-cloudnative/fluid/pull/2865 will fix it.
