### ISSUE TITLE
[FEATURES] Download swagger-codegen-cli.jar instead of storing it in hack/sdk/ directory in gen-sdk.sh script

### ISSUE THREAD

**Issue by cheyang** [fluid-cloudnative/fluid#2837]
**What feature you'd like to add:**

To avoid potential issues, it is not recommended to store the swagger-codegen-cli.jar file in the directory hack/sdk/. Instead, I recommend modifying the script at github.com/fluid-cloudnative/fluid/hack/sdk/gen-sdk.sh to first download the jar file from https://repo1.maven.org/maven2/io/swagger/codegen/v3/swagger-codegen-cli/3.0.41/swagger-codegen-cli-3.0.41.jar before proceeding with code generation. This ensures that the latest version of the jar file is always used and avoids potential issues with outdated jar files.

**Why is this feature needed:**

**Comment by wang-mask** [comment]
oh, it has been fixed.
