### ISSUE TITLE
[BUG] Metadata sync won't start when recreating an AlluxioRuntime with a same name

### ISSUE THREAD

**Issue by TrafalgarZZZ** [fluid-cloudnative/fluid#332]
**What is your environment(Kubernetes version, Fluid version, etc.)**
Fluid v0.4.0

**Describe the bug**

If I delete a AlluxioRuntime before its metadata synchronization process done and recreate one with the same name, the metadata sync process won't start.

This may lead to some problems like metadata synchronization won't start or the init image won't be re-setup. 

**What you expect to happen:**
Metadata sync should start when I create an AlluxioRuntime

**How to reproduce it**
1. Create an AlluxioRuntime, bind it to some dataset.
2. Delete the AlluxioRuntime before metadata synchronization is done.
3. Recreate one with the same name.
4. Found that metadata synchronization won't start.

**Additional Information**

**Comment by TrafalgarZZZ** [comment]
This may be the cause of this issue:

AlluxioRuntime controller maintains a map structure to record all the AlluxioEngine objects. However, it [adds an AlluxioEngine object to the map with the key "\<namespace\>-\<name\>"](https://github.com/fluid-cloudnative/fluid/blob/master/pkg/controllers/v1alpha1/alluxio/implement.go#L46) while try to [remove it with the key "\<namespace\>/\<name\>"](https://github.com/fluid-cloudnative/fluid/blob/master/pkg/controllers/v1alpha1/alluxio/implement.go#L70), which means the deletion is actually a no-op and the AlluxioEngine won't be removed when deleting the associated AlluxioRuntime

Metadata synchronization uses a channel defined in the AlluxioEngine object to get result asynchronously, under the circumstance where the AlluxioEngine will be reused instead of building a new one, the metadata synchronization won't start if a new AlluxioRuntime with the same name is created

**Comment by cheyang** [comment]
I think the channel should be destroyed when `engine.destroy()` .
