### ISSUE TITLE
[BUG] CSI Plugin cannot get node information in cluster created by Sealer

### ISSUE THREAD

**Issue by zhang-x-z** [fluid-cloudnative/fluid#3417]
**What is your environment(Kubernetes version, Fluid version, etc.)**
- K8s: 1.22.4
- Fluid: 0.9.1

What's more, I define the address of api server in the hosts file of every node in k8s cluster like this:
```
<my-ip> apiserver.cluster.local
```
**Describe the bug**
When create application pod after create dataset and runtime, CSI plugin goes wrong. Here is the log: 
```
I0823 13:41:49.865861 2138126 utils.go:97] GRPC call: /csi.v1.Node/NodeStageVolume
I0823 13:41:49.865879 2138126 utils.go:98] GRPC request: {"staging_target_path":"/var/lib/kubelet/plugins/kubernetes.io/csi/pv/default-test-dataset/globalmount","volume_capability":{"AccessType":{"Mount":{}},"access_mode":{"mode":3}},"volume_context":{"fluid_path":"/runtime-mnt/alluxio/default/test-dataset/alluxio-fuse","mount_type":"fuse.alluxio-fuse","runtime_name":"test-dataset","runtime_namespace":"default"},"volume_id":"default-test-dataset"}
I0823 13:41:49.865998 2138126 nodeserver.go:288] NodeStageVolume: Starting NodeStage with VolumeId: default-test-dataset, and VolumeContext: map[fluid_path:/runtime-mnt/alluxio/default/test-dataset/alluxio-fuse mount_type:fuse.alluxio-fuse runtime_name:test-dataset runtime_namespace:default]
I0823 13:41:49.866032 2138126 nodeserver.go:362] Get runtime namespace(default) and name(test-dataset) from volume context
E0823 13:41:49.867246 2138126 nodeserver.go:319] NodeStageVolume: can't get node pasak8s-18: Get "https://apiserver.cluster.local:6443/api/v1/nodes/pasak8s-18": dial tcp: lookup apiserver.cluster.local on 10.96.0.10:53: no such host
E0823 13:41:49.867278 2138126 utils.go:101] GRPC error: NodeStageVolume: can't get node pasak8s-18: Get "https://apiserver.cluster.local:6443/api/v1/nodes/pasak8s-18": dial tcp: lookup apiserver.cluster.local on 10.96.0.10:53: no such host
```
**What you expect to happen:**
CSI Plugin can create volume correctly.
**How to reproduce it**
Use the api server address defined in node's host file and create dataset & runtime & application pod.
**Additional Information**

**Comment by zhang-x-z** [comment]
In this commit: [Fix rbacs and limit CSI Plugin's node related access](https://github.com/fluid-cloudnative/fluid/commit/77c8110a3d1ec077ae2bce6bd88d296505db1550), the client to get the node information has been changed to created by [NewForConfig](https://pkg.go.dev/k8s.io/client-go@v0.23.0/kubernetes#NewForConfig), rather than by the manager of package controller-runtime.

**Comment by TrafalgarZZZ** [comment]
Since v0.8.6 and v0.9.0, Fluid borrows kubelet's KubeConfig(e.g. /etc/kubernetes/kubelet.conf) to access node info. This is because kubelet has been granted as a special role with [Node authorization](https://kubernetes.io/docs/reference/access-authn-authz/node/). This is mainly for security concern.

And back to the issue, it seems the kubelet's config uses a hostname to access K8s cluster. Givent that CSI Plugin will read the KubeConfig in a Pod, you should either install Fluid CSI Plugin with host dns, or add a special entry in your K8s cluster DNS to make it work.

**Comment by clearlove59** [comment]
Hello, could you tell me how to solve this problem?

**Comment by zhang-x-z** [comment]
> Hello, could you tell me how to solve this problem?

If you don't want to re-install fluid, you can insert a DNS record which points to your api server's IP in your K8s DNS. For me, I use the [hosts](https://coredns.io/plugins/hosts/) plugin in [CoreDNS](https://coredns.io/). You can find a similar plugin for your DNS.

**Comment by cheyang** [comment]
@zhang-x-z could you help enhance installation guide with special configuration on sealer?

**Comment by zhang-x-z** [comment]
> @zhang-x-z could you help enhance installation guide with special configuration on sealer?

@cheyang Add how to fix this problem in the installation guide. [PR](https://github.com/fluid-cloudnative/fluid/pull/3481)
