### ISSUE TITLE
[DOC] go client typo

### ISSUE THREAD

**Issue by JasonHe-WQ** [fluid-cloudnative/fluid#3629]
**Provide a link to that doc page:**

[go client](https://github.com/fluid-cloudnative/fluid/blob/master/docs/zh/dev/use_go_create_resource.md)

**What is the defect and your suggestions on improvement:**

https://github.com/fluid-cloudnative/fluid/blob/530fa504733125487f327d327492a1f2e86091b9/docs/zh/dev/use_go_create_resource.md?plain=1#L169

API could not be found, it may be adjusted and the new API is ```TieredStore: v1alpha1.TieredStore{```

**Comment by cheyang** [comment]
@JasonHe-WQ Thank you for figuring it！ Would you mind also fixing it?
