### ISSUE TITLE
[DOC] Dingding QR Code expired

### ISSUE THREAD

**Issue by zhenyu** [fluid-cloudnative/fluid#3680]
**Provide a link to that doc page:**
https://fluid-cloudnative.github.io/community/community.html
**What is the defect and your suggestions on improvement:**
Can not join the ding ding group chat with the embedded QR code

**Comment by RongGu** [comment]
Thank you very much for reporting this issue @zhenyu. I have submit a PR to fix this. https://github.com/fluid-cloudnative/fluid/pull/3691
