### ISSUE TITLE
[BUG] rename charts/juicefs/templates/worker/statefuleset.yaml to charts/juicefs/templates/worker/statefulset.yaml

### ISSUE THREAD

**Issue by Maslino** [fluid-cloudnative/fluid#3741]
**What is your environment(Kubernetes version, Fluid version, etc.)**

**Describe the bug**

There is a typographical error in JuiceFS worker statefulset chart filename (statefuleset.yaml).

**What you expect to happen:**

as the title explains

**How to reproduce it**

**Additional Information**

**Comment by cheyang** [comment]
@Maslino Thanks for your issue. Would you fix it and create a pull request?
