### ISSUE TITLE
Dataset requested

### ISSUE THREAD

**Issue by fenixjin** [fluid-cloudnative/fluid#3777]
I'm trying to reproduce your test on accelerate machine learning with fluid, and I have met problems with the right form of dataset, when I started the training job, I get following error : `ValueError: Found no files in --data_dir matching: /data/imagenet/train/train-*-of-*`
may I have a copy of the dataset you use in the machine learning demo ?

**Comment by cheyang** [comment]
@fenixjin I've sent you the download link by email. Please check your gmail. thanks.
