### ISSUE TITLE
[FEATURES] Metadata backup and master high-availability

### ISSUE THREAD

**Issue by xieydd** [fluid-cloudnative/fluid#384]
**What feature you'd like to add:**
Support Metadata backup or fault tolerance replication and master high-availability
**Why is this feature needed:**
In small scenario，metadata is even more important because of the high time cost of recovery.
So we need support metadata backup.

And if the node of master overload, master died,will influence the task. So we need support high-avaliability

**Comment by cheyang** [comment]
Reference: https://github.com/Alluxio/alluxio/issues/12571
https://github.com/coreos/etcd-operator/blob/master/doc/design/oss_backup.md
