### ISSUE TITLE
[BUG] Cannot exec a container that has stopped and stderr

### ISSUE THREAD

**Issue by xieydd** [fluid-cloudnative/fluid#395]
**What is your environment(Kubernetes version, Fluid version, etc.)**
kubernetes: 1.15.1
fluid: 0.4.0
**Describe the bug**
When delete a runtime and restart a runtime, even the componts of alluxio master worker and fuse is running, the runtime controller can not  run command in pod, the log show `cannot exec a container that has stopped and stderr`.

The situation will keep almost few hours, and the status of dataset will keep initial status. The `UFS TOTAL SIZE` and `CACHED PERCENTAGE` is empty.

**Comment by cheyang** [comment]
Does it relate to https://github.com/fluid-cloudnative/fluid/issues/332 ？

**Comment by xieydd** [comment]
The results are similar, but I don't see the log of the issue, not sure.
