### ISSUE TITLE
Report the use of components with vulnerabilities in fluid

### ISSUE THREAD

**Issue by HouqiyuA** [fluid-cloudnative/fluid#4054]
Dear Team Members:
Greetings! Our team is very interested in your project. we performed source code perspective security analysis (SCA) and vulnerability library association analysis on this project and found that components with vulnerabilities are still being used into this project.We would like to report this issue to you,so that you can fix and improve it accordingly. I add the details in json file below. Please confirm whether this problem really exists and confirm with us. Looking forward to hearing from you and discussing more details with us, thank you very much for your time and attention.

Note: Each "affect_components" field in the report represents the vulnerable component introduced by this project. The other is the vulnerability information associated with it.

Qiyu Hou

**Comment by cheyang** [comment]
Thank you for your interest in our project and for conducting the security analysis.

For any security-related issue, we would kindly ask you to follow this process: https://github.com/fluid-cloudnative/fluid/blob/master/SECURITY.md.

In fact, we have a continuous integration process in place to scan for image vulnerabilities to ensure the safety of Fluid's dependencies: https://github.com/fluid-cloudnative/fluid/blob/master/.github/dependabot.yml. We regularly run these scans and are committed to address any Critical or High-risk vulnerabilities within the current supported release range.

It's worth noting that scanners may generate some false positives. For instance, even if certain CVEs exist in the apiserver code, these do not affect any Fluid components. However, the scanner may still report them.  I think it will be much more helpful, if you can provide an explanation of why the vulnerability of dependency library poses a real (and not just theoretical) threat to users.
