### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by WangShuaiNWPU** [fluid-cloudnative/fluid#409]
**What is your environment(Kubernetes version, Fluid version, etc.)**
k8s 1.18.4   Fluid 0.4.0 腾讯云购买的容器服务
**Describe the bug**
根据https://github.com/fluid-cloudnative/fluid/blob/master/docs/zh/userguide/get_started.md 的指导跑demo，发现demo-app一直是pending状态
<img width="588" alt="截屏2020-11-27 下午5 20 13" src="https://user-images.githubusercontent.com/20381919/100432741-fcf44900-30d4-11eb-98ef-652ffc2788ec.png">

**What you expect to happen:**
demo-app正常运行
**How to reproduce it**
稳定复现
**Additional Information**
[diagnose_fluid_1606468590.tar.gz](https://github.com/fluid-cloudnative/fluid/files/5607082/diagnose_fluid_1606468590.tar.gz)

**Comment by cheyang** [comment]
@XIAO-HOU 请分析一下，谢谢。

**Comment by XIAO-HOU** [comment]
> **What is your environment(Kubernetes version, Fluid version, etc.)**
> k8s 1.18.4 Fluid 0.4.0 腾讯云购买的容器服务
> **Describe the bug**
> 根据https://github.com/fluid-cloudnative/fluid/blob/master/docs/zh/userguide/get_started.md 的指导跑demo，发现demo-app一直是pending状态
> <img alt="截屏2020-11-27 下午5 20 13" width="588" src="https://user-images.githubusercontent.com/20381919/100432741-fcf44900-30d4-11eb-98ef-652ffc2788ec.png">
> 
> **What you expect to happen:**
> demo-app正常运行
> **How to reproduce it**
> 稳定复现
> **Additional Information**
> [diagnose_fluid_1606468590.tar.gz](https://github.com/fluid-cloudnative/fluid/files/5607082/diagnose_fluid_1606468590.tar.gz)

你是配了StorageClass吗？你可以问一下腾讯客服。

**Comment by WangShuaiNWPU** [comment]
> > **What is your environment(Kubernetes version, Fluid version, etc.)**
> > k8s 1.18.4 Fluid 0.4.0 腾讯云购买的容器服务
> > **Describe the bug**
> > 根据https://github.com/fluid-cloudnative/fluid/blob/master/docs/zh/userguide/get_started.md 的指导跑demo，发现demo-app一直是pending状态
> > <img alt="截屏2020-11-27 下午5 20 13" width="588" src="https://user-images.githubusercontent.com/20381919/100432741-fcf44900-30d4-11eb-98ef-652ffc2788ec.png">
> > **What you expect to happen:**
> > demo-app正常运行
> > **How to reproduce it**
> > 稳定复现
> > **Additional Information**
> > [diagnose_fluid_1606468590.tar.gz](https://github.com/fluid-cloudnative/fluid/files/5607082/diagnose_fluid_1606468590.tar.gz)
> 
> 你是配了StorageClass吗？你可以问一下腾讯客服。

@XIAO-HOU 我没有配置Storage class，但是我在腾讯云控制台看到有如下storage class
<img width="1025" alt="截屏2020-11-28 下午12 34 27" src="https://user-images.githubusercontent.com/20381919/100493843-3d57d380-3176-11eb-8255-a3f76165bbd7.png">
我咨询一下腾讯云客服。谢谢

**Comment by WangShuaiNWPU** [comment]
@cheyang @XIAO-HOU 
 我问了下腾讯云客服，他们会创建一个默认的storage class，名字叫cbs。同时他们定位后台日志有打印：failed to provision volume with StorageClass "cbs": claim.Spec.Selector is not supported for dynamic provisioning on GCE 。
我理解，Fluid的目的是将pvc demo绑定到pv demo上，但是却走了dynamically provision流程。 我查到了资料：
https://kubernetes.io/docs/concepts/storage/persistent-volumes/#class-1 有下面一段话：
<img width="930" alt="截屏2020-11-28 下午2 45 49" src="https://user-images.githubusercontent.com/20381919/100495771-bdd3ff80-3189-11eb-98f7-614180e0e1cc.png">

所以，我想是不是因为demo pvc没有指定storageClassName所以走了绑定default storage class的流程，没有绑定静态的pv demo。
因此，根据下面截图的说明，是不是应该在pvc里加上storageClassName: "" ，来指定将demo pvc绑定到没有设置存储类的 demo PV 。 
这样对于创建了默认storage class的k8s环境也能兼容了。
<img width="918" alt="截屏2020-11-28 下午3 02 00" src="https://user-images.githubusercontent.com/20381919/100495923-f0322c80-318a-11eb-9e42-56f4b29217da.png">

**Comment by fredkan** [comment]
@WangShuaiNWPU 如果集群中配置了default storageclass，就会在pvc没有定义storageclass的情况下去做provision。

1. 如果要想把已有的pvc、pv做绑定，那就都给pvc、pv加上storageclassName，这样就可以匹配了（加上label、selector可以更加精确的匹配）。
2. 要是想做动态provision，也最好给pvc加上storageclassname，不要用default，后面也容易混淆；
3. 最好把集群中的default storageclass去掉default属性；

**Comment by XIAO-HOU** [comment]
> @cheyang @XIAO-HOU
> 我问了下腾讯云客服，他们会创建一个默认的storage class，名字叫cbs。同时他们定位后台日志有打印：failed to provision volume with StorageClass "cbs": claim.Spec.Selector is not supported for dynamic provisioning on GCE 。
> 我理解，Fluid的目的是将pvc demo绑定到pv demo上，但是却走了dynamically provision流程。 我查到了资料：
> https://kubernetes.io/docs/concepts/storage/persistent-volumes/#class-1 有下面一段话：
> <img alt="截屏2020-11-28 下午2 45 49" width="930" src="https://user-images.githubusercontent.com/20381919/100495771-bdd3ff80-3189-11eb-98f7-614180e0e1cc.png">
> 
> 所以，我想是不是因为demo pvc没有指定storageClassName所以走了绑定default storage class的流程，没有绑定静态的pv demo。
> 因此，根据下面截图的说明，是不是应该在pvc里加上storageClassName: "" ，来指定将demo pvc绑定到没有设置存储类的 demo PV 。
> 这样对于创建了默认storage class的k8s环境也能兼容了。
> <img alt="截屏2020-11-28 下午3 02 00" width="918" src="https://user-images.githubusercontent.com/20381919/100495923-f0322c80-318a-11eb-9e42-56f4b29217da.png">

我已经针对这个问题进行了修改，您能再在您的环境上测试一下吗，谢谢。

**Comment by WangShuaiNWPU** [comment]
> > @cheyang @XIAO-HOU
> > 我问了下腾讯云客服，他们会创建一个默认的storage class，名字叫cbs。同时他们定位后台日志有打印：failed to provision volume with StorageClass "cbs": claim.Spec.Selector is not supported for dynamic provisioning on GCE 。
> > 我理解，Fluid的目的是将pvc demo绑定到pv demo上，但是却走了dynamically provision流程。 我查到了资料：
> > https://kubernetes.io/docs/concepts/storage/persistent-volumes/#class-1 有下面一段话：
> > <img alt="截屏2020-11-28 下午2 45 49" width="930" src="https://user-images.githubusercontent.com/20381919/100495771-bdd3ff80-3189-11eb-98f7-614180e0e1cc.png">
> > 所以，我想是不是因为demo pvc没有指定storageClassName所以走了绑定default storage class的流程，没有绑定静态的pv demo。
> > 因此，根据下面截图的说明，是不是应该在pvc里加上storageClassName: "" ，来指定将demo pvc绑定到没有设置存储类的 demo PV 。
> > 这样对于创建了默认storage class的k8s环境也能兼容了。
> > <img alt="截屏2020-11-28 下午3 02 00" width="918" src="https://user-images.githubusercontent.com/20381919/100495923-f0322c80-318a-11eb-9e42-56f4b29217da.png">
> 
> 我已经针对这个问题进行了修改，您能再在您的环境上测试一下吗，谢谢。

可以的。请问我怎么获取并安装新版本的fluid呢？

**Comment by XIAO-HOU** [comment]
您可以用这个[fluid.tar.gz](https://github.com/fluid-cloudnative/fluid/files/5629434/fluid.tar.gz)@WangShuaiNWPU
