### ISSUE TITLE
[BUG] Does not support K3S

### ISSUE THREAD

**Issue by lay-g** [fluid-cloudnative/fluid#4104]
**What is your environment(Kubernetes version, Fluid version, etc.)**
K3S: 1.29.4
Fluid: v1.0

**Describe the bug**
DaemonSet csi-nodeplugin-fluid can't deploy on k3s.

![image](https://github.com/fluid-cloudnative/fluid/assets/19180533/822f04b6-d9f9-466e-8dc2-9b598342acfd)

**What you expect to happen:**

**How to reproduce it**
helm install --namespace=fluid-system --create-namespace fluid fluid/fluid

**Additional Information**

**Comment by cheyang** [comment]
Thank you for finding it. I think it's a feature request.  We didn't test it on K3s before.

**Comment by baowj-678** [comment]
I will take a look at this.

**Comment by baowj-678** [comment]
The directory for storing the [kube config files](https://docs.k3s.io/cluster-access) and certificate files in k3s is different from that in k8s. You can complete the installation by setting the `kubeConfigFile` and `certDir` in the `values.yaml` file.
~~~
csi:
  kubelet:
    kubeConfigFile: /etc/rancher/k3s/k3s.yaml
    certDir: /var/lib/rancher/k3s/agent
~~~

**Comment by lay-g** [comment]
Sorry, I have not updated the latest situation. I tried copying the configuration file to /etc/kubernetes/kubelet.conf, and then it worked fine. Thanks for everyone's responses.
