### ISSUE TITLE
[Question] Does Fluid itself support report metrics to Prometheus?

### ISSUE THREAD

**Issue by yanghua** [fluid-cloudnative/fluid#4133]
In the docs, I only find [one document](https://github.com/fluid-cloudnative/fluid/blob/master/docs/zh/operation/monitoring.md) about monitoring. But it's about monitoring runtime/engine. My question is " Does fluid itself support to be monitored via reporting metrics to Prometheus?"

**Comment by cheyang** [comment]
Thank you for the question. Fluid has supported the metrics reporting in the components. For example, it's in https://github.com/fluid-cloudnative/fluid/blob/master/cmd/dataset/app/dataset.go#L92. And we will provide grafana dashboard JSON.

**Comment by yanghua** [comment]
Thanks for your answer. Got it.
