### ISSUE TITLE
[FEATURES]  csi-node-driver-registrarimage support for arm architecture

### ISSUE THREAD

**Issue by Gentleelephant** [fluid-cloudnative/fluid#4182]
**What feature you'd like to add:**

fluidcloudnative/csi-node-driver-registrar:v2.3.0 image dont support arm architecture.
<img width="1039" alt="image" src="https://github.com/fluid-cloudnative/fluid/assets/35139861/c2bb73ab-a8d1-43e2-bc09-900b54155ee2">

**Why is this feature needed:**

**Comment by Gentleelephant** [comment]
https://github.com/kubernetes-csi/node-driver-registrar/tree/release-2.3

**Comment by airlenet** [comment]
Has the image in the fluidcloudnative namespace been modified? Two ImageIDs were found to be different (x86)

fluidcloudnative/csi-node-driver-registrar                                    v2.3.0                 b31c21be01cc   2 years ago     22.6MB
registry.k8s.io/sig-storage/csi-node-driver-registrar                         v2.3.0                 368ee7d6e60f   3 years ago     18.7MB
