### ISSUE TITLE
[BUG]Docker build warning for unconsumed build-args [HELM_VERSION]  in Dockerfile.crds

### ISSUE THREAD

**Issue by cheyang** [fluid-cloudnative/fluid#4298]
**What is your environment(Kubernetes version, Fluid version, etc.)**

**Describe the bug**

When running the Docker build command with the specified build arguments --build-arg TARGETARCH=amd64 --build-arg HELM_VERSION=helm-v3.11.3, a warning is generated indicating that the build-arg HELM_VERSION was not consumed during the build process. Here is the output from the build process:

```bash
Sending build context to Docker daemon 134.6MB
Step 1/7: FROM alpine@sha256:11e21d7b981a59554b3f822c49f6e9f57b6068bb74f49c4cd5cc4c663c7e5160
...
[Warning] One or more build-args [HELM_VERSION] were not consumed

```

Command Used:

```bash
docker build --build-arg TARGETARCH=amd64 --build-arg HELM_VERSION=helm-v3.11.3 . -f docker/Dockerfile.crds -t fluidcloudnative/fluid-crd-upgrader:v1.0.2
```

The build-arg HELM_VERSION specified in the Docker build command was not utilized in Dockerfile during the build process, leading to the warning message. 

**What you expect to happen:**

**How to reproduce it**

**Additional Information**

**Comment by omerap12** [comment]
Sorry about that 😞 . here is the fix
