### ISSUE TITLE
[BUG]jindo runtime 定时预热功能失败

### ISSUE THREAD

**Issue by ruan875417** [fluid-cloudnative/fluid#4363]
**What is your environment(Kubernetes version, Fluid version, etc.)**
alluixo
controller image: fluidcloudnative/alluxioruntime-controller:v1.0.1-14eda3b
runtime image: alluxio/alluxio-dev:2.9.0
fuse image: alluxio/alluxio-dev:2.9.0

**Describe the bug**
用jindo dataload功能时 定时去预热 
![dataload](https://github.com/user-attachments/assets/dbb21e8d-ae79-438c-9869-771e278627c5)
现在会报错 然后dataload的pod也没创建 
![dataload2](https://github.com/user-attachments/assets/b658af3f-4758-49bc-bf1a-19ddfe910604)

**What you expect to happen:**
定时预热功能正常

**How to reproduce it**

dataload yaml

apiVersion: data.fluid.io/v1alpha1
kind: DataLoad
metadata:
  name: rwl-fluid-jindo-dataload-demo1
spec:
  loadMetadata: true
  dataset:
    name: rwl-fluid-jindo-demo1
    namespace: default
  policy: Cron
  schedule: "*/2 * * * *" # Run every 2 min
  target:
    - path: /pytorch

**Additional Information**

**Comment by TrafalgarZZZ** [comment]
@ruan875417 Thanks for reporting this. Looks like the same problem in #4358 . Should be fixed in #4360 . Please have a try on the latest Fluid version.
