### ISSUE TITLE
[DOC] 关于“数据集分布式缓存系统”配置构建的问题

### ISSUE THREAD

**Issue by Lorenz5622** [fluid-cloudnative/fluid#4403]
您好，我在阅读本项目对应的论文时发现，您在文中提到了使用数据集特征和机器候选配置生成fluid dataset的分布式缓存系统，我想深入了解一下相关的技术细节，例如使用了数据集的哪些特征，如何提取特征等等。感谢您！

**Comment by TrafalgarZZZ** [comment]
@Lorenz5622 使用了数据集的文件数量和总数据集大小作为数据集侧的输入特征，Concat上若干个备选的配置参数（包括线程池大小、CPU、内存、元信息缓存池大小等），整体作为一个随机森林模型的输入向量，计算得到分数。随机森林模型是基于历史数据预训练得到的，预训练的输入是上述输入特征向量，预训练的输出是输入向量的条件下几个常见缓存I/O操作耗时优化程度的加权分数。
