### ISSUE TITLE
[FEATURES]Enable hdfs special configuration 

### ISSUE THREAD

**Issue by lilyzhoupeijie** [fluid-cloudnative/fluid#502]
**What feature you'd like to add:**
When HDFS has non-default configurations, we need to  configure Alluxio servers to access HDFS with the proper configuration file.    
we will do as follows,both the workers and master are needed:
copy or make symbolic links from hdfs-site.xml and core-site.xml from my Hadoop installation into ${ALLUXIO_HOME}/conf. and then set the property alluxio.underfs.hdfs.configuration in conf/alluxio-site.properties to point to my hdfs-site.xml and core-site.xml. 
**Why is this feature needed:**
to enable HA hdfs or other special hdfs configuration

**Comment by cheyang** [comment]
Maybe we need follow the way of spark operator: https://github.com/GoogleCloudPlatform/spark-on-k8s-operator
