### ISSUE TITLE
[FEATURES] Add Cache hit ratio for dataset

### ISSUE THREAD

**Issue by cheyang** [fluid-cloudnative/fluid#526]
**What feature you'd like to add:**

**Why is this feature needed:**

Update Per minute

1. Total Cache Ratio = （BytesReadRemote+ BytesReadLocal）/（BytesReadRemote+ BytesReadLocal+ BytesReadUfs）

2. Local Cache Ratio = （ BytesReadLocal）/（BytesReadRemote+ BytesReadLocal+ BytesReadUfs）

3. Total Cache Throughput  = （BytesReadRemoteThroughput + BytesReadLocalThroughput）/（BytesReadRemoteThroughput + BytesReadLocalThroughput + BytesReadUfsThroughput）

4. Local Cache Throughput =  （BytesReadLocalThroughput）/（BytesReadRemoteThroughput + BytesReadLocalThroughput + BytesReadUfsThroughput）

5. Freed file count: Master.FilesFreed  (Type: COUNTER, Value: 0)

6. Freed file ops: Master.FreeFileOps  (Type: COUNTER, Value: 0)

```
alluxio fsadmin report metrics
Cluster.BytesReadDomain  (Type: COUNTER, Value: 0B)
Cluster.BytesReadDomainThroughput  (Type: GAUGE, Value: 0B/MIN)
Cluster.BytesReadLocal  (Type: COUNTER, Value: 1860.06MB)
Cluster.BytesReadLocalThroughput  (Type: GAUGE, Value: 21.88MB/MIN)
Cluster.BytesReadPerUfs.UFS:oss:%2F%2Foffline-training-project-norisk-2%2F  (Type: COUNTER, Value: 5109.22GB)
Cluster.BytesReadRemote  (Type: COUNTER, Value: 284.58GB)
Cluster.BytesReadRemoteThroughput  (Type: GAUGE, Value: 3428.37MB/MIN)
Cluster.BytesReadUfsAll  (Type: COUNTER, Value: 5109.22GB)
Cluster.BytesReadUfsThroughput  (Type: GAUGE, Value: 60.11GB/MIN)
Cluster.BytesWrittenDomain  (Type: COUNTER, Value: 0B)
Cluster.BytesWrittenDomainThroughput  (Type: GAUGE, Value: 0B/MIN)
Cluster.BytesWrittenLocal  (Type: COUNTER, Value: 0B)
Cluster.BytesWrittenLocalThroughput  (Type: GAUGE, Value: 0B/MIN)
```

**Comment by xieydd** [comment]
for cli?
