### ISSUE TITLE
[BUG]When deleting dataset, the label "fluid_exclusive: {$Namespace}_{Dataset}" may have not been deleted

### ISSUE THREAD

**Issue by yangyuliufeng** [fluid-cloudnative/fluid#553]
**What is your environment(Kubernetes version, Fluid version, etc.)**
Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.9-aliyun.1", GitCommit:"4f7ea78", GitTreeState:"", BuildDate:"2020-05-08T07:35:38Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
fluid 0.5
**Describe the bug**
When deleting dataset, the label "fluid_exclusive: {$Namespace}_{Dataset}" may have not been deleted
![My Mac-2021-01-31-19-40-24](https://user-images.githubusercontent.com/30432274/106384864-277dbd80-6408-11eb-8589-8d073d94820a.png)

**What you expect to happen:**
when deleting dataset, this label should been deleted so that other dataset can be scheduled to this node
**How to reproduce it**
So far, I have not figured out the scene of this bug. 
the same action, sometimes this bug will occur, sometimes not
**Additional Information**
I and  @TrafalgarZZZ have searched this bug for several days, but we have not figured out the reason.

**Comment by cheyang** [comment]
@xieydd Please take a look at this issue. Thanks.

**Comment by cheyang** [comment]
https://github.com/fluid-cloudnative/fluid/blob/master/pkg/ddc/alluxio/shutdown.go#L185

I think we can check it's better to check the exclusive label for the specified dataset exist rather than checking runtimeInfo.

**Comment by cheyang** [comment]
1.getNodes by labels
2.check if the node has the exclusive label for the dataset, then clean it up.

**Comment by xieydd** [comment]
I think if node label num not change but content change will not update, in https://github.com/fluid-cloudnative/fluid/blob/master/pkg/ddc/alluxio/shutdown.go#L210, how bout delete this condition.

**Comment by xieydd** [comment]
> 1.getNodes by labels
> 2.check if the node has the exclusive label for the dataset, then clean it up.

good suggestion, i will change it

**Comment by cheyang** [comment]
fixed by #560
