### ISSUE TITLE
[BUG]Alluxio image which master depended has security issue

### ISSUE THREAD

**Issue by goodoid** [fluid-cloudnative/fluid#565]
**What is your environment(Kubernetes version, Fluid version, etc.)**
fluid master
**Describe the bug**
```text
registry.cn-huhehaote.aliyuncs.com/alluxio/alluxio:2.4.1-1-SNAPSHOT-9833d5f (alpine 3.9.4)
==========================================================================================
Total: 194 (UNKNOWN: 0, LOW: 98, MEDIUM: 74, HIGH: 20, CRITICAL: 2)
```

**What you expect to happen:**
update alluxio image version in docker
**How to reproduce it**
```shell
trivy image registry.cn-huhehaote.aliyuncs.com/alluxio/alluxio:2.4.1-1-SNAPSHOT-9833d5f
```
**Additional Information**
alluxio security issue https://github.com/Alluxio/alluxio/issues/12781

**Comment by cheyang** [comment]
fixed by #566
