### ISSUE TITLE
[BUG]Dataset ufsTotal status been calculating after created for a long time

### ISSUE THREAD

**Issue by goodoid** [fluid-cloudnative/fluid#567]
**What is your environment(Kubernetes version, Fluid version, etc.)**
fluid master commit id f4aaeb4

**Describe the bug**
The dataset UFS TOTAL SIZE been calculating after created 

**What you expect to happen:**

**How to reproduce it**
create a dataset with 2 pvc mount points
```text
apiVersion: data.fluid.io/v1alpha1
kind: Dataset
metadata:
  name: test-dataset-2pvc
  namespace: default
spec:
  mounts:
  - mountPoint: pvc://fashion-mnist-pvc
    name: fashion-mnist-pvc-acc
  - mountPoint: pvc://mnist-data
    name: mnist-data-acc
  nodeAffinity: {}
```

runtime conf
```text
apiVersion: data.fluid.io/v1alpha1
kind: AlluxioRuntime
metadata:
  name: test-dataset-2pvc
  namespace: default
spec:
  alluxioVersion: {}
  data:
    pin: false
    replicas: 1
  fuse:
    resources: {}
  initUsers:
    resources: {}
  jobMaster:
    resources: {}
  jobWorker:
    resources: {}
  master:
    resources: {}
  replicas: 4
  tieredstore:
    levels:
    - high: "0.99"
      low: "0.8"
      mediumtype: SSD
      path: /var/lib/docker/alluxio
      quota: 150Gi
  worker:
    resources: {}
```

**Additional Information**
```text
NAME                UFS TOTAL SIZE   CACHED    CACHE CAPACITY   CACHED PERCENTAGE   PHASE     AGE
test-dataset-2pvc   [Calculating]    0.00B     600.00GiB                            Bound     12h
```

**Comment by TrafalgarZZZ** [comment]
Hi, the calculation time of `Ufs Total SIze` is related to how many files in your dataset. So do you know how many files are there in your two pvcs?

**Comment by goodoid** [comment]
> n
fashion-mnist-pvc-acc from an oss storage which has 119169 object
mnist-data has 9 files

**Comment by goodoid** [comment]
> Hi, the calculation time of `Ufs Total SIze` is related to num of files in your dataset. So do you know how many files are there in your two pvcs?

fashion-mnist-pvc-acc from an oss storage which has 119169 object
mnist-data has 9 files
