### ISSUE TITLE
Can not delete the node label "fluid_exclusive" when deleting a dataset[BUG]

### ISSUE THREAD

**Issue by XIAO-HOU** [fluid-cloudnative/fluid#574]
**What is your environment(Kubernetes version, Fluid version, etc.)**
commit id 9e77feb

**Describe the bug**
The label "fluid_exclusive" is not deleted when deleting a dataset. What's more, as long as the label is unempty, the created runtime will not ready(only the master is ready) even though the dataset name is corresponding to the label. After I delete the label manually, the runtime will be ready after a while.

**What you expect to happen:**
When I delete a dataset, the label "fluid_exclusive" corresponding to it should be deleted as well.

**How to reproduce it**
1. create a dataset.
2. delete the dataset.
3. create a dataset again.

**Additional Information**

**Comment by cheyang** [comment]
What's the commit id you are testing with? Show the image tag

**Comment by XIAO-HOU** [comment]
9e77feb，I think it is the latest commit id.

**Comment by XIAO-HOU** [comment]
> What's the commit id you are testing with? Show the image tag

9e77feb，I think it is the latest commit id.

**Comment by TrafalgarZZZ** [comment]
I think I found the cause:
https://github.com/fluid-cloudnative/fluid/blob/master/pkg/ddc/alluxio/shutdown.go#L199 uses different representation of exclusive dataset from https://github.com/fluid-cloudnative/fluid/blob/master/pkg/utils/dataset/lifecycle/node.go#L138

Working on it.
