### ISSUE TITLE
[FEATURES]When fuse in global mode, currentFuseNumberScheduled and desiredFuseNumberScheduled are 0

### ISSUE THREAD

**Issue by yangyuliufeng** [fluid-cloudnative/fluid#628]
**What feature you'd like to add:**
When fuse in global mode, currentFuseNumberScheduled and desiredFuseNumberScheduled are 0
I think the number should be "NA" or "global"
**Why is this feature needed:**

**Comment by XIAO-HOU** [comment]
I can fix it. Please assign this issue to me. Thanks @cheyang
