### ISSUE TITLE
Update alluxio version

### ISSUE THREAD

**Issue by xieydd** [fluid-cloudnative/fluid#634]
**What feature you'd like to add:**
I notice alluxio 2.5.0 version released. can we change the script and update the alluxio version.
cc @cheyang

**Comment by cheyang** [comment]
2.5.0 is not dedicated for AI. 2.4.2 which is owned by Bin is for AI.

**Comment by apc999** [comment]
I will release 2.5.0-1 shortly, Alluxio versions like 2.x.x-x is owned and patched by me.

**Comment by xieydd** [comment]
ok, thanks for bin's support.
