### ISSUE TITLE
[BUG]Dataload's status should be Pending when the status of dataset is Calculating

### ISSUE THREAD

**Issue by ldd91** [fluid-cloudnative/fluid#673]
**What is your environment(Kubernetes version, Fluid version, etc.)**
Fluid:0.5.0
**Describe the bug**
My dataset is about 800G,all the data are small files.I create dataset and runtime,the status of dataset is Calculating.I create a dataload and the status of dataload is Loading 

The following Scenarios should notify the end user:

1. the dataload's namespace is different from dataset
2. the path to load doesn't exist

**What you expect to happen:**

**How to reproduce it**

**Additional Information**

**Comment by xieydd** [comment]
@ldd91 Hi, dongdong, you can try the new commit.

**Comment by ldd91** [comment]
@xieydd Thanks,I will have a try

**Comment by cheyang** [comment]
> @xieydd Thanks,I will have a try

@ldd91 how about the test? can we close it now?

**Comment by cheyang** [comment]
Close it since it's not active for a long time. Feel free to reopen it.
