### ISSUE TITLE
[FEATURES]The method of calculating image address should be unified

### ISSUE THREAD

**Issue by yangyuliufeng** [fluid-cloudnative/fluid#680]
**What feature you'd like to add:**
The method of calculating image address should be unified
**Why is this feature needed:**
Now, there are lots of methods of calculating image address . Such as alluxio-master, inituser of alluxio, inituser of databackup, they have different logics.
I think we'd better to write an unified method.

**Comment by XIAO-HOU** [comment]
I can address this problem. Please assign this issue to me @cheyang
