### ISSUE TITLE
[FEATURES] open rest port  for connecting

### ISSUE THREAD

**Issue by lilyzhoupeijie** [fluid-cloudnative/fluid#691]
We need to connnect to fluid(alluxio) via rest api in order to ls,mkdir,delete files ....bacause the python sdk ,the go sdk are both realized by rest.
so it would be better to open the proxy port when fluid is started.
the proxy will be open as follows in alluxio:
sh alluxio-start.sh proxy

**Comment by cheyang** [comment]
fixed by #689
