### ISSUE TITLE
[BUG] Node labels exceeds maximum length limit for long namespace and name

### ISSUE THREAD

**Issue by 2sin18** [fluid-cloudnative/fluid#704]
**What is your environment(Kubernetes version, Fluid version, etc.)**

Kubernetes version: 1.18
Fluid version: 0.6.0

**Describe the bug**
Label name and values in Kubernetes has a maximum length limit of 63 characters as request by [RFC-1123](https://tools.ietf.org/html/rfc1123). However, Fluid adds labels to nodes with long prefix (see below examples), which limits the total length of namespace and name of datasets to 63 - 41 = 22.

```
data.fluid.io/storage-human-jindo-disk-{namespace}-{name}=1B,
data.fluid.io/storage-human-jindo-total-{namespace}-{name}=1B,
data.fluid.io/storage-jindo-{namespace}-{name}=true,
data.fluid.io/storage-{namespace}-{name}=true,
fluid_exclusive={namespace}_{name},
```

**What you expect to happen:**

Reduce length of node label prefix.

**How to reproduce it**

Create a dataset with namespace and name that exceeds 22 characters.

**Additional Information**

None.

**Comment by cheyang** [comment]
fixed by #696
