### ISSUE TITLE
[BUG] The env HOME conflict with local HOME when developed on the Mac

### ISSUE THREAD

**Issue by allenhaozi** [fluid-cloudnative/fluid#767]
https://github.com/fluid-cloudnative/fluid/blob/edf70609379e6108918bd503a5cd45f22d157b98/pkg/utils/charts.go#L41

The env `HOME` conflict with local `HOME` when developed on the Mac

Can we upgrade to something else like `FLUID_HOME`, `ALLUXIO_CHARTS_DIR` , ...

**Comment by cheyang** [comment]
You can use `ln -s {} ~/charts` to fix this. It's by design.
