### ISSUE TITLE
After the dataset is applied to the cluster, the master pod waits for a long time to start

### ISSUE THREAD

**Issue by lilyzhoupeijie** [fluid-cloudnative/fluid#768]
**What is your environment(Kubernetes version, Fluid version, etc.)**
k8s:v1.18.6
fluid:dataset-controller:v0.5.0-064f786
**Describe the bug**
After the dataset is applied to the cluster, the master pod waits for a long time to start,we wait for 8 minutes
**What you expect to happen:**
After the dataset is applied to the cluster, it will be better if the master pod start as soon as possible

**Comment by allenhaozi** [comment]
Please provide the log of Aluxio, the more detailed the better

**Comment by TrafalgarZZZ** [comment]
Currently, Fluid controllers(e.g. AlluxioRuntime Controller) use only one worker for reconciliation. Given that there are many AlluxioRuntime CRs, there is a chance that reconciliation for one CR may be delayed especially when a single reconciliation process takes significant time cost.

Maybe an extra controller that is responsible for synchronizing status of Datasets and AlluxioRuntimes is the best choice, we can reconsider about this in the future.

To avoid such a situation,  for now I'm going to give a workaround by **allowing users to adjust parallelism for reconciliation workers**
