### ISSUE TITLE
Update website to fluidcn.org or fluid-cloudnative.io

### ISSUE THREAD

**Issue by caniszczyk** [fluid-cloudnative/fluid#807]
Now that the project is a CNCF project, we should update the website location

http://pasa-bigdata.nju.edu.cn/fluid/index.html -> fluidcn.org or equivalent :)

**Comment by xieydd** [comment]
I think it is already done, how about closing the issue.

**Comment by RongGu** [comment]
Yes. The new webiste is here  fluid-cloudnative.github.io/
