### ISSUE TITLE
In concurrency, it may be better to use patch rather than update in updating the rosources.

### ISSUE THREAD

**Issue by littletiger123** [fluid-cloudnative/fluid#811]
In Kubernetes, there are two ways to inform the API server to update the resources--UPDATE and PATCH. 

UPDATE is a total replacement that will replace the resources in the API server with the object in memory.  So we need to add the mutex in development if we use concurrency in the controller otherwise we may lose the previous modifications. 

PATCH is an incremental replacement that will only replace the properties added and the other contents will remain in the API server. In this way, we only need to add the mutex in several special situations such as counting the dataset in the specific node.
It may be more efficient.

**Comment by TrafalgarZZZ** [comment]
closed by #877
