### ISSUE TITLE
RequeueIfError don't requeue when err is not nil

### ISSUE THREAD

**Issue by wangyanghack** [fluid-cloudnative/fluid#831]
https://github.com/fluid-cloudnative/fluid/blob/ec45f935a8a8d700ba09a34aa5ef56d54ef8e7c4/pkg/utils/crtl_utils.go#L51

Should it return `ctrl.Result{Requeue: true}`?
If it is,I can fix it.

**Comment by cheyang** [comment]
Thank you for spotting it. Welcome to contribute. But for this case, it's as design because controller runtime will re-queue it  if the error is not nil.

**Comment by wangyanghack** [comment]
sorry,I understand it
